### ISSUE TITLE
New meeting type = "In Person"

### ISSUE THREAD

**Issue by sfconn** [code4recovery/12-step-meeting-list#351] opened 2021-05-27 00:20 UTC
**Is your feature request related to a problem? Please describe.**
We at EastBayAA.org would like a new meeting type = In-Person.  Some of our meetings never closed, so the type = Re-Opened does not apply to them.  Additionally, our volunteers on the phone line and chat line seem to be more comfortable with the wording "In-Person" over "Re-Opened".  It goes well with the existing type of "In Person and Virtual".   Maybe you should consider a new type of "Virtual" as well, but honestly, that is pretty much covered by listing the online meeting credentials.  But just a thought.

**Describe the solution you'd like**

**Describe alternatives you've considered**

I am not comfortable adding a custom meeting type.  But if you can's support this, I will find someone who can help me add it to our site only.  

**Additional context**
LOVE the existing tool.  So thankful for you creating it.

**Comment by tech2serve** [comment] 2021-05-27 13:06
Duplicate of #312 and several other closed issues. 

Use search or peruse the issues for more details.

Our goal is to have this feature available in beta soon.

**Closed by tech2serve** 2021-05-27 13:06 UTC
Labels: duplicate

**Comment by brianw-area24** [comment] 2021-05-27 15:16
In looking at the East Bay Intergroup site, it looks like someone has already customized the "types" on this site because "In Person & Virtual" and Re-Opened are not types provided by the TSML plugin. After the new version comes out, and you install it, you may want to undo these customizations on your site. We'd be happy to help with how to do that if you open a new issue at that time

**Comment by sfconn** [comment] 2021-05-27 15:32
Hi Brian,

 

Thanks for your quick reply here and on GitHub.  Not sure who added those meeting types for me/us.  I will ask around and get them to coach me how to also add “In Person”.

 

Thanks for all you do.

 

Steve Conn

510-220-6710

**Comment by brianw-area24** [comment] 2021-05-27 15:39
You may want to wait until the next version of the plugin comes out. It will track meetings by online, in-person, hybrid, and temporarily closed. This last one will likely get renamed, maybe to something like temporarily inactive.

If you add an in-person type now, you may be making more work for yourself in the near future.

Brian W

**Comment by sfconn** [comment] 2021-05-27 15:40
Brian,

 

Do you have an estimate on a release date?  I am new to GitHub, is there a was I can see proposed release dates there?

 

Steve Conn

510-220-6710
