### ISSUE TITLE
Allow any type of URL in the Teleconference URL field

### ISSUE THREAD

**Issue by ronraney** [code4recovery/12-step-meeting-list#136] opened 2020-07-29 22:06 UTC
**Is your feature request related to a problem? Please describe.**
Our district uses short URLs or custom URLs to link to our Zoom meetings online. We don't like to explicitly share our Zoom links because of Zoom bombing. We created short URLs to redirect to the Zoom meetings. The bombers can use these if they want but perhaps their scraping tools are only looking for "zoom.us" or some sort of flag.

**Describe the solution you'd like**
Please allow us to add custom URLs to the CSV, in the teleconference URL field.

**Describe alternatives you've considered**
I don't know why there's a constraint in place for this, but you could restrict it to http: and https: to validate the fields.

**Additional context**
Relates to my closed issue #135

**Comment by joshreisner** [comment] 2020-07-30 15:00
For background: we aren't aware of any confirmed instances of URL scraping on recovery websites, but we have added functionality to prevent it anyway to 12 Step Meeting List. On the meeting listing page the Join with <Provider> button does not contain the online meeting URL, that is only added by javascript at the time the user clicks the button. (Screenshot below.)

Users who click the conference button expect to be taken to a conferencing service, so we added link checking to help meet those expectations consistently. 

That said, you're welcome to extend list of providers, or disable checking altogether. To disable it, add this to your theme's functions.php file:

```
$tsml_conference_providers = null;
```

Or instead you could extend it with: 

```
$tsml_conference_providers += array(
    'aa-ksdist23.org' => 'District 23 Secure URL',
);
```

![url-security](https://user-images.githubusercontent.com/1551689/88938453-42455e80-d23a-11ea-9cd9-aded0aa55556.png)

**Comment by ronraney** [comment] 2020-07-30 20:54
Awesome, thank you.

**Comment by ronraney** [comment] 2020-08-15 20:03
I tried using the second option. Any idea why I'm getting this error below? I'm assuming our server is using PHP 5 and there is something being used from newer PHP. Not sure which operand is unsupported.

_The code snippet you are trying to save produced a fatal error on line 3:

Unsupported operand types__

**Comment by joshreisner** [comment] 2020-08-15 20:05
Hey @ronraney ok maybe your PHP version doesn't like += for arrays. Try this instead:

```
$tsml_conference_providers = array_merge($tsml_providers, array(
    'aa-ksdist23.org' => 'District 23 Secure URL',
));
```

**Comment by ronraney** [comment] 2020-08-15 20:11
That was a FAST response. I appreciate it. 

This didn't work because it's not showing the meeting URLs. We are using not-secure HTTP. Does that make a difference? 

I think I may just have to use the Zoom IDs instead.

**Comment by joshreisner** [comment] 2020-08-15 20:21
Sorry could you walk me through what happens? You try to add the custom URL on the backend and it disappears?

It may be that the url you're pasting isn't for some reason matching `aa-ksdist23.org` but I doubt it's to do with HTTPS. What's the URL you're pasting in? We need to get this to match the left side of the array we're putting in, eg `zoom.us` is already an option built in, we're going to add to that

**Comment by ronraney** [comment] 2020-08-15 20:26
Here's an example of a short link/redirect we are using:
http://aa-ksdist23.org/wp/wsg ... goes to ...
us02web.zoom.us/j/81589556356

(I changed the Zoom number)

**Comment by joshreisner** [comment] 2020-08-15 20:42
Ok thanks. So in terms of what happens: you enter the URL in the backend and it's gone after you hit Update?

**Comment by ronraney** [comment] 2020-08-15 20:47
We advertise our meetings and use vanity URLs for all of our Zoom meetings. On the front end, people only see the short URLs, until it redirects them to the Zoom meeting.

If I enter the aa-ksdist23.org address into the CSV/Meeting Guide database, it doesn't show a Meeting URL on the individual meeting page. Only allowed domains will render a Meeting URL on this page.

I tried adding the code above to functions.php, using our domain name, and it doesn't work. If I upload the CSV, it doesn't give me an error, but if I go to a meeting page, there is not meeting URL listed.

**Comment by ronraney** [comment] 2020-08-15 20:49
I'm not sure if this will be useful to anyone else, but I went ahead and put the Zoom URLs in our CSV file. If you want to try to resolve this for other people's sake, that's cool. If not, I am satisfied with moving on from this. I hate to take up your time on this. Thanks

**Comment by k8fish3r** [comment] 2020-08-31 12:16
Have to admit I wish the plugin supported entirely free plugin Jitsi, but mindful beyond Greenpeace, Mashable, Engadget, New York Times etc Jitsi isnt well known. 

Fairly averse to the amount of money Zoom must be making from 12 step programmes forced online who need to register to reach more than X people over more than 40 minutes. Wish more were aware of the completely free options.

Jitsi > 350 people, free forever as long as you want to meet.

**Comment by joshreisner** [comment] 2020-09-01 02:37
@k8fish3r we're happy to add support for additional providers. Please create a new issue and give us examples of Jitsi meeting URLs. You're also welcome to add providers to your own website.

> Have to admit I wish the plugin supported entirely free plugin Jitsi, but mindful beyond Greenpeace, Mashable, Engadget, New York Times etc Jitsi isnt well known.
> 
> Fairly averse to the amount of money Zoom must be making from 12 step programmes forced online who need to register to reach more than X people over more than 40 minutes. Wish more were aware of the completely free options.
> 
> Jitsi upto 75 people, free forever as long as you want to meet.
> 
> Thankful for the hundreds / thousands including yourself offering free open source solutions to everyday problems.

**Comment by crispyatl** [comment] 2020-10-12 17:56
In regards to supporting other providers, Josh, I see you can set it to null to disable validation, but what about falling back on a default?  That is, if a meeting URL is given which is not in variables.php/$tsml_conference_providers, set it to something generic like 'Web Link'.

**Comment by tech2serve** [comment] 2020-10-14 17:18
I'm going to close this because the OP was was basically satisfied, and @k8fish3r didn't come back/create a new issue.

**Closed by tech2serve** 2020-10-14 17:18 UTC
