### ISSUE TITLE
Improve success/failure feedback when entering an address or updating a meeting

### ISSUE THREAD

**Issue by tech2serve** [code4recovery/12-step-meeting-list#47] opened 2019-11-20 00:54 UTC
**Is your feature request related to a problem? Please describe.**
Yes.

A number of sites using the 12-step-meeting-list plugin experience difficulties with geocoding certain addresses in their local area. With one example, the site’s geocoding worked during the initial creation of a meeting, but subsequent changes to the meeting are not possible because the geocoding fails and the `Update` button is not active. 

Other users have reported issues with the `Update` button being grayed out, and they’re not sure why. Subsequent investigation determines they have an address that is not seen as valid by Google, but this isn’t clearly displayed to the user on the admin page. Ofttimes copying and pasting the address from the maps.google.com page resolves the issue even though the addresses were fundamentally the same. 

Even when an incorrect address is the source of the problem, it is difficult for inexperienced users to realize the address they’ve entered is the problem based on the lack of information provided by the plugin. Likewise, when the address is confirmed valid but something else is causing a geocoding problem, no debug information is provided to the user. 

The lack of feedback makes it difficult to debug problems locally and remotely.

**Describe the solution you'd like**

When the address is geocoded successfully, the form should show a green check mark next to the input field. When the geocoding is not successful, a red “x” should be displayed, and additional error information should be displayed to help the user determine the corrective course of action.

The debugging information should appear near the address field so users are able to quickly capture and report in a support request or bug report.

**Describe alternatives you've considered**

- Automatically generating bug reports when geocoding fails.
- Add logging that could then be sent to the developers
- Instead of a green check, just have the field become dark gray until a successful geocode is completed.

**Additional context**
This will help troubleshoot problems and improve trust for the users.

**Comment by joshreisner** [comment] 2019-11-20 01:03
I can probably do this. I would like to review this with specific cases before work is done though.

In my many years of experience with this, the most common reason for a greyed out button was a javascript error from another plugin interfering with geocoding.

I am aware of a recent case also that had to do with the billing, which is a separate issue and may need to be addressed first.

**Comment by tech2serve** [comment] 2019-11-20 01:33
The case that I cannot solve yet is Ogden, Utah, with one specific address. As I chatted in #slack, we deleted the meetings in question, then reentered them. That worked fine until we tried to edit the meeting information and the `Update` is greyed. Ogden has 166 meetings in 47 locations; I can't say with complete certainty, but this appears to be the only validated issue. 

To add further intrigue, if I go to the front end and display [one of the two meetings](https://northernutahaa.org/meetings/clearfield-group/?tsml-day=6) at the location (525 E 200 South, Clearfield, UT) it is currently showing the correct address, but if I click on `Directions` I get routed to "155 E 200 S, Clearfield, UT". If I mimic this on my dev site, I get routed to the correct address.

When I inspect the elements of the site in question, the lat/lng are empty; when I inspect mine their values are populated.

**Comment by joshreisner** [comment] 2019-11-20 02:26
Ok so the issue with directions is not related. When we route people to addresses, we route them to the latitude and longitude, per request from alcoholics-anonymous.eu. Your directions provider (Apple Maps on iOS, Google otherwise) will then reverse geocode that to get the address. The pin should be in the right place at least, although the mismatching address is not ideal. If you want to get into more discussion on that let’s create a new issue. 

Not sure what the issue is with this address, it looks perfectly valid. When I geocode it I get ‘525 E 200 S, Clearfield, UT 84015, USA‘

Let’s find a time to connect on it.

**Comment by brianw-area24** [comment] 2019-11-20 06:07
I'm still trying to figure out how the plugin works, so I might be totally off base here. I'm looking at the tsml_geocode function at line 487 of includes/functions.php, specifically I'm looking at lines 495-500. It looks to me like there is a cache of addresses, stored in the database, which is checked before going out to Google. And if the address you're looking up is in that cache, it uses the cached version instead of going out to Google.

So, if your address, was once wrong in Google, it could have gotten into the cache on the production server. If the address was since corrected by Google, the production server would still be finding the incorrect entry in cache. However, because our test sites do not have it in cache, we would get the correct address from Google.

If this is the case, then it would explain why their site is showing the wrong address in the background, but ours show the right address.

**Comment by tech2serve** [comment] 2019-11-20 15:40
I poked into the database for the site and found 14 references to "525 E 200 S" in the `tsml_addresses` option. The first entries don't appear to have an associated lat/lng. The correct lat/lng appears to be included 7 times.

**Comment by joshreisner** [comment] 2019-11-20 16:22
Thanks. It’s not surprising that there would be redundant references. It’d be great if you could export that JSON value and sort and format it so we can inspect it on Friday to see if there’s a problem.

**Comment by joshreisner** [comment] 2019-11-20 16:23
(Or we can do it together on Friday)

**Comment by joshreisner** [comment] 2019-11-23 04:04
@tech2serve found three related caches in the JSON for 

* 525 E 200 S, Clearfield, UT 84015, USA
* 525 E 200 South, Ogden, UT
* 525 E 200 South, Clearfield, Utah

The first of these had empty values, which is not good. I think the fix for this is to do two things:

1. don't cache empty values, and
2. clean up any cached entries that have empty values

The ideas for interface improvements are definitely things we should do at some point, but to address the specific problem that we were having here I will be adding a PR to address issues 1 and 2.

**Comment by brianw-area24** [comment] 2019-11-23 06:29
I've been toying around with the idea of creating an additional plugin, maybe "TSML Support Assistant" which would give the site owner, and hopefully us, a page to see things that hopefully would help us with the inner workings of the TSML plugin. The Support Assistant page could show us things like:
- Version of TSML
- Version of WordPress
- Version of PHP
- Possibly full phpinfo()
- Number of meetings
- Number of unpublished meetings
- Addresses in the Geo cache
- Meetings in the meeting cache
- Settings values of the plugin ie Sharing: restricted or open
- Whether a MapBox or Google Key is set
- Name/version of theme

In addition, it would be really nice if it could be used to:
- Remove a single entry from the geo cache
- Add an entry to the geo cache (rather than adding it to functions.php of the theme)
- Maybe remove the geo cache
- Remove the meeting cache

All this could be done in the TSML plugin itself, but I'm thinking a separate plugin might be good, to help keep the TSML plugin as lean as possible. Lot's of details to be worked out, just something I wanted to throw out there.

**Closed** 2020-03-01 22:53 UTC
