### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by OSAwebsite** [code4recovery/12-step-meeting-list#629] opened 2022-01-06 19:27 UTC
### Contact Details

os.website.a86@gmail.com

### Website With Issue

al-anon.alateen.on.ca

### What happened?

A bug happened!
'Types' are no longer imported.

### TSML Version

Latest (default)

### Wordpress Version

Latest (default)

### What browsers are you seeing the problem on?

Safari

**Comment by brianw-area24** [comment] 2022-01-07 14:04
Duplicate of Issue #633

**Closed by brianw-area24** 2022-01-07 14:04 UTC
Labels: bug
