### ISSUE TITLE
Warnings When Lat/Lon Not Set

### ISSUE THREAD

**Issue by lloy0076** [code4recovery/12-step-meeting-list#400] opened 2021-06-30 02:49 UTC
**Describe the bug**

3.11.0

It seems that the latest update throws several warnings:

    if (!isset($locations[$meeting['location_id']])) {
        $locations[$meeting['location_id']] = array(
            'name' => $meeting['location'],
            'latitude' => $meeting['latitude'] - 0,
            'longitude' => $meeting['longitude'] - 0,
            'url' => $meeting['location_url'], //can't use link here, unfortunately
            'formatted_address' => $meeting['formatted_address'],
            'meetings' => array(),
        );
    }

Notice: Undefined index: latitude in /home/q0afnjbk/public_html/wp-content/plugins/12-step-meeting-list/templates/archive-meetings.php on line 540

Notice: Undefined index: longitude in /home/q0afnjbk/public_html/wp-content/plugins/12-step-meeting-list/templates/archive-meetings.php on line 541

... I removed the tsml-cache once or twice to see if it was a failed to encode issue.

If I had to guess some meetings don't have latitudes/longitudes because they're online only or something silly like that.

**Comment by lloy0076** [comment] 2021-06-30 02:50
NB. I've kludged that method to:

    if (!isset($locations[$meeting['location_id']]) && isset($meeting['latitude'])) {
        $locations[$meeting['location_id']] = array(
            'name' => $meeting['location'],
            'latitude' => $meeting['latitude'] - 0,
            'longitude' => $meeting['longitude'] - 0,
            'url' => $meeting['location_url'], //can't use link here, unfortunately
            'formatted_address' => $meeting['formatted_address'],
            'meetings' => array(),
        );

just to silence this error.

**Comment by lloy0076** [comment] 2021-06-30 02:51
[{"id":2653,"name":"Canton Saturday Night Live","slug":"canton-saturday-night-live","notes":"Because of current guidelines, attendees will be asked to: bring a mask, practise social distance and use hand sanitizer when appropriate.\n\nA full statement can be found at the following URL:\n\nhttps:\/\/aa-stlawrenceny.org\/canton-saturday-night-group-reopening-requirements\/) or click on the","updated":"2021-06-30 02:20:08","location_id":2268,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/canton-saturday-night-live\/","day":6,"time":"20:00","end_time":"21:00","time_formatted":"8:00 pm","attendance_option":"in_person","types":["D","O"],"location":"Canton","location_notes":"Parking is available in rear of church.","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/uu-canton\/","formatted_address":"3 1\/2 E Main St, Canton, NY 13617, USA","latitude":44.5962645,"longitude":-75.1678314,"region_id":36,"region":"Eastern Ontario 83","group_id":2654,"group":"Canton Saturday Night Group","district":"District 42","district_id":37},{"id":2638,"name":"Closed Discussion","slug":"closed-discussion","updated":"2021-06-16 02:07:25","location_id":2639,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/closed-discussion\/","day":0,"time":"10:00","end_time":"11:00","time_formatted":"10:00 am","attendance_option":"in_person","types":["C","D"],"location":"Ogdensburg","location_notes":"This is part of the Ogdensburg Rescue Squad location; use the left side entrance, \"Public Gatherings.\" It was formerly \"Hacketts Store\".","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/ogdensburg\/","formatted_address":"1223 Pickering St, Ogdensburg, NY 13669, USA","latitude":44.6865695,"longitude":-75.4864452,"region_id":36,"region":"Eastern Ontario 83","group_id":2640,"group":"Riverside Group","district":"District 42","district_id":37,"last_contact":"2021-06-03","contact_1_name":"Gary G","contact_1_email":"gary.gagnon2@verizon.net"},{"id":2627,"name":"Open Discussion","slug":"heuvelton-open-discussion","notes":"Masks are not required if you are vaccinated.","updated":"2021-06-11 00:41:09","location_id":2628,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/heuvelton-open-discussion\/","day":2,"time":"19:30","end_time":"20:30","time_formatted":"7:30 pm","attendance_option":"in_person","types":["D","O"],"location":"Heuvelton","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/heuvelton\/","formatted_address":"44 Lisbon St, Heuvelton, NY 13654, USA","latitude":44.6173752,"longitude":-75.4077161,"region_id":36,"region":"Eastern Ontario 83"},{"id":2496,"name":"Open Discussion","slug":"open-discussion","updated":"2021-06-30 02:29:37","location_id":2497,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/open-discussion\/","day":1,"time":"19:30","end_time":"20:30","time_formatted":"7:30 pm","attendance_option":"in_person","types":["D","O","X","XB"],"location":"Colton","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/colton\/","formatted_address":"4897a NY-56, Colton, NY 13625, USA","latitude":44.5565183,"longitude":-74.9454439,"region_id":36,"region":"Eastern Ontario 83"},{"id":2380,"name":"Came to Believe Open Discussion","slug":"came-to-believe-2","updated":"2021-06-30 02:44:07","location_id":2383,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/came-to-believe-2\/","day":3,"time":"19:00","end_time":"20:00","time_formatted":"7:00 pm","attendance_option":"in_person","types":["D","O"],"location":"Canton","location_notes":"The meeting happens under the pavilion in \"Bend in the River Park\" next to the Canton Recreation Office.\n\nParking and rest rooms are available.","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/canton-3\/","formatted_address":"90 Lincoln St, Canton, NY 13617, USA","latitude":44.5850341,"longitude":-75.1740772,"region_id":36,"region":"Eastern Ontario 83","group_id":2385,"group":"Came to Believe Group of Alcoholics Anonymous","district":"District 42","district_id":37},{"id":2377,"name":"Tuesday Night Primary Purpose Group","slug":"tuesday-night-primary-purpose-group","updated":"2021-06-30 02:30:18","location_id":2378,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/tuesday-night-primary-purpose-group\/","day":2,"time":"20:00","end_time":"21:00","time_formatted":"8:00 pm","attendance_option":"in_person","types":["D","O"],"location":"Norwood","location_notes":"This meeting is in St. Phillip's Episcopal Church premises.","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/norwood\/","formatted_address":"42 S Main St, Norwood, NY 13668, USA","latitude":44.7485648,"longitude":-74.9931649,"region_id":36,"region":"Eastern Ontario 83","group_id":2379,"group":"Tuesday Night Primary Purpose Group","district":"District 42","district_id":37},{"id":2374,"name":"Parishville Group","slug":"parishville-group","updated":"2021-05-29 12:27:35","location_id":2375,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/parishville-group\/","day":4,"time":"20:00","end_time":"21:00","time_formatted":"8:00 pm","attendance_option":"in_person","types":["D","O"],"location":"Parishville","location_notes":"The meeting is in the Town Hall located on the main intersection.","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/parishville\/","formatted_address":"1172 NY-72, Potsdam, NY 13676, USA","latitude":44.627387,"longitude":-74.8697302,"region_id":36,"region":"Eastern Ontario 83","group_id":2376,"group":"Parishville Group","district":"District 42","district_id":37},{"id":2329,"name":"Candlelight Meeting","slug":"candlelight-meeting","notes":"This meeting is at 41 Court Street at the United Methodist Church.","updated":"2021-04-20 01:45:20","location_id":2333,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/candlelight-meeting\/","day":0,"time":"19:00","end_time":"20:00","time_formatted":"7:00 pm","attendance_option":"in_person","types":["CAN","D","O"],"location":"Canton","location_notes":"Parking is available in rear of church.","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/canton\/","formatted_address":"41 Court St, Canton, NY 13617, USA","latitude":44.5974227,"longitude":-75.1698942,"region_id":36,"region":"Eastern Ontario 83"},{"id":2326,"name":"As Bill Sees It","slug":"as-bill-sees-it","notes":"A live group meeting - safely sanitized, social distanced, with masks required until further notice. Format is group discussion relative to A.A.'s co-founder Bill W.'s selected writings, \"As Bill Sees It\".\n\nBring your own beverage.","updated":"2021-04-11 10:15:23","location_id":2268,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/as-bill-sees-it\/","day":1,"time":"07:00","end_time":"08:00","time_formatted":"7:00 am","attendance_option":"in_person","types":["ABSI","EN","LIT","O","X"],"location":"Canton","location_notes":"Parking is available in rear of church.","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/uu-canton\/","formatted_address":"3 1\/2 E Main St, Canton, NY 13617, USA","latitude":44.5962645,"longitude":-75.1678314,"region_id":36,"region":"Eastern Ontario 83"},{"id":2321,"name":"Open Discussion","slug":"friday-night-discussion","updated":"2021-03-15 07:53:56","location_id":2322,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/friday-night-discussion\/","day":5,"time":"19:00","end_time":"20:00","time_formatted":"7:00 pm","attendance_option":"in_person","types":["D","O"],"location":"Ogdensburg","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/united-methodist-church\/","formatted_address":"627 Caroline St, Ogdensburg, NY 13669, USA","latitude":44.694083,"longitude":-75.4880702,"region_id":36,"region":"Eastern Ontario 83","group_id":2323,"group":"Friday Night Serenity Group","district":"District 42","district_id":37},{"id":2319,"name":"Came to Believe Big Book Study","slug":"monday-night-came-to-believe","notes":"Password: 9G9KFn","updated":"2021-06-30 02:31:37","location_id":2268,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/monday-night-came-to-believe\/","day":1,"time":"20:00","end_time":"21:00","time_formatted":"8:00 pm","attendance_option":"online","conference_url":"https:\/\/us02web.zoom.us\/j\/8797863127?pwd=NE5sSWZyTmR2Z2ZuMTFBd1kvWGY1UT09","types":["B","LIT","O","ONL","TC"],"location":"Canton","location_notes":"Parking is available in rear of church.","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/uu-canton\/","formatted_address":"3 1\/2 E Main St, Canton, NY 13617, USA","latitude":44.5962645,"longitude":-75.1678314,"region_id":36,"region":"Eastern Ontario 83","group_id":2385,"group":"Came to Believe Group of Alcoholics Anonymous","district":"District 42","district_id":37},{"id":2317,"name":"Serenity Place (Open Discussion)","slug":"serenity-place-open-discussion-4","notes":"Please see https:\/\/www.39serenityplace.com\/clubhouse-online for more info.","updated":"2021-06-30 02:38:46","location_id":2313,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/serenity-place-open-discussion-4\/","day":5,"time":"19:00","end_time":"20:00","time_formatted":"7:00 pm","attendance_option":"online","conference_url":"https:\/\/www.gotomeet.me\/39SerenityPlace\/clubhouse","conference_phone":"8668994679","conference_phone_notes":"856-476-517#","types":["D","O","ONL","TC"],"location":"Serenity Place","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/serenity-place\/","formatted_address":"175 E Orvis St, Massena, NY 13662, USA","region_id":36,"region":"Eastern Ontario 83","group_id":2314,"group":"Serenity Place","website":"https:\/\/www.39serenityplace.com\/","email":"clubhouse@39serenityplace.com","phone":"3152507410","mailing_address":"175 E. Orivs St, Massena, NY, 13662","contact_1_name":"Clubhouse","contact_1_email":"clubhouse@39serenityplace.com","contact_1_phone":"3152507410"},{"id":2316,"name":"Serenity Place (Open Discussion)","slug":"serenity-place-open-discussion-3","notes":"Please see https:\/\/www.39serenityplace.com\/clubhouse-online for more info.","updated":"2021-06-30 02:38:58","location_id":2313,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/serenity-place-open-discussion-3\/","day":3,"time":"19:00","end_time":"20:00","time_formatted":"7:00 pm","attendance_option":"online","conference_url":"https:\/\/www.gotomeet.me\/39SerenityPlace\/clubhouse","conference_phone":"8668994679","conference_phone_notes":"Access Code : 856-476-517#","types":["D","O","ONL","TC"],"location":"Serenity Place","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/serenity-place\/","formatted_address":"175 E Orvis St, Massena, NY 13662, USA","region_id":36,"region":"Eastern Ontario 83","group_id":2314,"group":"Serenity Place","website":"https:\/\/www.39serenityplace.com\/","email":"clubhouse@39serenityplace.com","phone":"3152507410","mailing_address":"175 E. Orivs St, Massena, NY, 13662","contact_1_name":"Clubhouse","contact_1_email":"clubhouse@39serenityplace.com","contact_1_phone":"3152507410"},{"id":2315,"name":"Serenity Place (Open Discussion)","slug":"serenity-place-open-discussion-2","notes":"Please see https:\/\/www.39serenityplace.com\/clubhouse-online for more info.","updated":"2021-06-30 02:39:05","location_id":2313,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/serenity-place-open-discussion-2\/","day":1,"time":"19:00","end_time":"20:00","time_formatted":"7:00 pm","attendance_option":"online","conference_url":"https:\/\/www.gotomeet.me\/39SerenityPlace\/clubhouse","conference_phone":"8668994679","conference_phone_notes":"Access Code : 856-476-517#","types":["D","O","ONL","TC"],"location":"Serenity Place","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/serenity-place\/","formatted_address":"175 E Orvis St, Massena, NY 13662, USA","region_id":36,"region":"Eastern Ontario 83","group_id":2314,"group":"Serenity Place","website":"https:\/\/www.39serenityplace.com\/","email":"clubhouse@39serenityplace.com","phone":"3152507410","mailing_address":"175 E. Orivs St, Massena, NY, 13662","contact_1_name":"Clubhouse","contact_1_email":"clubhouse@39serenityplace.com","contact_1_phone":"3152507410"},{"id":2312,"name":"Serenity Place (Open Discussion)","slug":"serenity-place-open-discussion","notes":"This meeting is currently online only.\n\nPlease see https:\/\/www.39serenityplace.com\/clubhouse-online for more info.","updated":"2021-06-30 02:38:09","location_id":2313,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/serenity-place-open-discussion\/","day":0,"time":"12:00","end_time":"13:00","time_formatted":"Noon","attendance_option":"online","conference_url":"https:\/\/www.gotomeet.me\/39SerenityPlace\/clubhouse","conference_phone":"8668994679","conference_phone_notes":"856-476-517#","types":["D","O","ONL","TC"],"location":"Serenity Place","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/serenity-place\/","formatted_address":"175 E Orvis St, Massena, NY 13662, USA","region_id":36,"region":"Eastern Ontario 83","group_id":2314,"group":"Serenity Place","website":"https:\/\/www.39serenityplace.com\/","email":"clubhouse@39serenityplace.com","phone":"3152507410","mailing_address":"175 E. Orivs St, Massena, NY, 13662","contact_1_name":"Clubhouse","contact_1_email":"clubhouse@39serenityplace.com","contact_1_phone":"3152507410"},{"id":2305,"name":"Came to Believe Meditation Meeting","slug":"came-to-believe","notes":"Password: 9G9KFn","updated":"2021-06-30 02:31:57","location_id":2268,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/came-to-believe\/","day":5,"time":"20:00","end_time":"21:00","time_formatted":"8:00 pm","attendance_option":"online","conference_url":"https:\/\/us02web.zoom.us\/j\/8797863127?pwd=NE5sSWZyTmR2Z2ZuMTFBd1kvWGY1UT09","types":["D","EN","LIT","MED","ONL","TC"],"location":"Canton","location_notes":"Parking is available in rear of church.","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/uu-canton\/","formatted_address":"3 1\/2 E Main St, Canton, NY 13617, USA","latitude":44.5962645,"longitude":-75.1678314,"region_id":36,"region":"Eastern Ontario 83","group_id":2385,"group":"Came to Believe Group of Alcoholics Anonymous","district":"District 42","district_id":37},{"id":2294,"name":"Women's Meeting","slug":"womens-meeting","updated":"2021-06-30 02:32:13","location_id":2290,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/womens-meeting\/","day":1,"time":"19:00","end_time":"20:00","time_formatted":"7:00 pm","attendance_option":"online","conference_url":"https:\/\/us02web.zoom.us\/j\/82887453426?pwd=YjFrR2FqVnFzdFFqYUI0bk42Z2RSUT09","types":["C","D","EN","W","ONL","TC"],"location":"Potsdam","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/potsdam-2\/","formatted_address":"42 Elm St, Potsdam, NY 13676, USA","latitude":44.6701258,"longitude":-74.9807659,"region_id":36,"region":"Eastern Ontario 83"},{"id":2289,"name":"Friday Night Responsibility","slug":"friday-night-responsibility-group","notes":"Please bring your mask; social distancing will be required.","updated":"2020-07-22 22:13:27","location_id":2290,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/friday-night-responsibility-group\/","day":5,"time":"20:00","end_time":"21:00","time_formatted":"8:00 pm","attendance_option":"in_person","types":["B","D","LIT"],"location":"Potsdam","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/potsdam-2\/","formatted_address":"42 Elm St, Potsdam, NY 13676, USA","latitude":44.6701258,"longitude":-74.9807659,"region_id":36,"region":"Eastern Ontario 83","group_id":2291,"group":"Friday Night Responsibility","district":"District 42","district_id":37},{"id":2287,"name":"Fall Island Big Book Study","slug":"fall-island-big-book-study","notes":"Password: 947076\n\nUntil further notice we are only meeting online.","updated":"2021-06-30 02:33:22","location_id":2256,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/fall-island-big-book-study\/","day":0,"time":"19:00","end_time":"20:00","time_formatted":"7:00 pm","attendance_option":"online","conference_url":"https:\/\/us02web.zoom.us\/j\/650029279?pwd=ZnErUkxMNjZiME9HdDZBLzVxRE4xdz09","conference_phone":"+19294362866","types":["B","C","D","EN","ONL","TC"],"location":"Potsdam","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/potsdam\/","formatted_address":"8 Maple St, Potsdam, NY 13676, USA","latitude":44.6673094,"longitude":-74.987851,"region_id":36,"region":"Eastern Ontario 83","group_id":2288,"group":"Fall Island Big Book Study","district":"District 42","district_id":37},{"id":2266,"name":"Nooners","slug":"nooners-3","notes":"On Saturdays we meet in person; on other days our meetings are online.","updated":"2021-05-29 12:54:15","location_id":2256,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/nooners-3\/","day":6,"time":"12:00","end_time":"13:00","time_formatted":"Noon","attendance_option":"in_person","types":["CF","D","EN","O"],"location":"Potsdam","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/potsdam\/","formatted_address":"8 Maple St, Potsdam, NY 13676, USA","latitude":44.6673094,"longitude":-74.987851,"region_id":36,"region":"Eastern Ontario 83","group_id":2257,"group":"Nooners","district":"District 42","district_id":37,"website":"https:\/\/www.potsdamnooners.club\/","email":"contact [at] potsdamnooners.club"},{"id":2265,"name":"Nooners","slug":"nooners-2","notes":"We are meeting online Monday to Friday inclusive; but our Saturday meeting is in person.","updated":"2021-06-30 02:35:10","location_id":2256,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/nooners-2\/","day":5,"time":"12:00","end_time":"13:00","time_formatted":"Noon","attendance_option":"online","conference_url":"https:\/\/www.freeconferencecall.com\/wall\/potsdamnooners","conference_phone":"2093999610","types":["CF","D","EN","O","ONL","TC"],"location":"Potsdam","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/potsdam\/","formatted_address":"8 Maple St, Potsdam, NY 13676, USA","latitude":44.6673094,"longitude":-74.987851,"region_id":36,"region":"Eastern Ontario 83","group_id":2257,"group":"Nooners","district":"District 42","district_id":37,"website":"https:\/\/www.potsdamnooners.club\/","email":"contact [at] potsdamnooners.club"},{"id":2264,"name":"Nooners","slug":"nooners","notes":"We are meeting online Monday to Friday inclusive; but our Saturday meeting is in person.","updated":"2021-06-30 02:35:45","location_id":2256,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/nooners\/","day":4,"time":"12:00","end_time":"13:00","time_formatted":"Noon","attendance_option":"online","conference_url":"https:\/\/www.freeconferencecall.com\/wall\/potsdamnooners","conference_phone":"2093999610","types":["CF","DR","EN","O","ONL","TC"],"location":"Potsdam","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/potsdam\/","formatted_address":"8 Maple St, Potsdam, NY 13676, USA","latitude":44.6673094,"longitude":-74.987851,"region_id":36,"region":"Eastern Ontario 83","group_id":2257,"group":"Nooners","district":"District 42","district_id":37,"website":"https:\/\/www.potsdamnooners.club\/","email":"contact [at] potsdamnooners.club"},{"id":2263,"name":"Nooners","slug":"2263","notes":"We are meeting online Monday to Friday inclusive; but our Saturday meeting is in person.","updated":"2021-06-30 02:35:56","location_id":2256,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/2263\/","day":3,"time":"12:00","end_time":"13:00","time_formatted":"Noon","attendance_option":"online","conference_url":"https:\/\/www.freeconferencecall.com\/wall\/potsdamnooners","conference_phone":"2093999610","types":["B","CF","EN","O","ONL","TC"],"location":"Potsdam","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/potsdam\/","formatted_address":"8 Maple St, Potsdam, NY 13676, USA","latitude":44.6673094,"longitude":-74.987851,"region_id":36,"region":"Eastern Ontario 83","group_id":2257,"group":"Nooners","district":"District 42","district_id":37,"website":"https:\/\/www.potsdamnooners.club\/","email":"contact [at] potsdamnooners.club"},{"id":2262,"name":"Nooners","slug":"2262","notes":"We are meeting online Monday to Friday inclusive; but our Saturday meeting is in person.","updated":"2021-06-30 02:36:17","location_id":2256,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/2262\/","day":1,"time":"12:00","end_time":"13:00","time_formatted":"Noon","attendance_option":"online","conference_url":"https:\/\/www.freeconferencecall.com\/wall\/potsdamnooners","conference_phone":"2093999610","types":["CF","EN","O","ONL","TC"],"location":"Potsdam","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/potsdam\/","formatted_address":"8 Maple St, Potsdam, NY 13676, USA","latitude":44.6673094,"longitude":-74.987851,"region_id":36,"region":"Eastern Ontario 83","group_id":2257,"group":"Nooners","district":"District 42","district_id":37,"website":"https:\/\/www.potsdamnooners.club\/","email":"contact [at] potsdamnooners.club"},{"id":2255,"name":"Nooners","slug":"2255","notes":"We are meeting online Monday to Friday inclusive; but our Saturday meeting is in person.","updated":"2021-06-30 02:36:29","location_id":2256,"url":"https:\/\/aa-stlawrenceny.org\/meetings\/2255\/","day":2,"time":"12:00","end_time":"13:00","time_formatted":"Noon","attendance_option":"online","conference_url":"https:\/\/www.freeconferencecall.com\/wall\/potsdamnooners","conference_phone":"2093999610","types":["11","CF","EN","MED","O","ONL","TC"],"location":"Potsdam","location_url":"https:\/\/aa-stlawrenceny.org\/locations\/potsdam\/","formatted_address":"8 Maple St, Potsdam, NY 13676, USA","latitude":44.6673094,"longitude":-74.987851,"region_id":36,"region":"Eastern Ontario 83","group_id":2257,"group":"Nooners","district":"District 42","district_id":37,"website":"https:\/\/www.potsdamnooners.club\/","email":"contact [at] potsdamnooners.club"}]

**Comment by lloy0076** [comment] 2021-06-30 02:52
[tsml-cache-5202e6201c.json.txt](https://github.com/code4recovery/12-step-meeting-list/files/6737681/tsml-cache-5202e6201c.json.txt)

**Comment by tech2serve** [comment] 2021-07-01 02:07
So even with an approximate address (used by online meetings), the lat/lng will still be populated.

If they are not set, let's look closer at some details.

How are you getting meeting data into the site?

For a meeting in which you're seeing this behavior, please send a screen cap of the admin edit page for that meeting.

What is your site link?

**Comment by lloy0076** [comment] 2021-07-01 02:49
![image](https://user-images.githubusercontent.com/1174532/124057385-5b7bff80-d9f5-11eb-947b-778984f8106f.png)

**Comment by lloy0076** [comment] 2021-07-01 02:49
I don't KNOW which meetings are causing this yet.

**Comment by lloy0076** [comment] 2021-07-01 02:51
array(32) {
  ["id"]=>
  int(2315)
  ["name"]=>
  string(32) "Serenity Place (Open Discussion)"
  ["slug"]=>
  string(32) "serenity-place-open-discussion-2"
  ["notes"]=>
  string(74) "Please see https://www.39serenityplace.com/clubhouse-online for more info."
  ["updated"]=>
  string(19) "2021-06-30 02:39:05"
  ["location_id"]=>
  int(2313)
  ["url"]=>
  string(70) "https://aa-stlawrenceny.org/meetings/serenity-place-open-discussion-2/"
  ["day"]=>
  int(1)
  ["time"]=>
  string(5) "19:00"
  ["end_time"]=>
  string(5) "20:00"
  ["time_formatted"]=>
  string(7) "7:00 pm"
  ["attendance_option"]=>
  string(6) "online"
  ["conference_url"]=>
  string(49) "https://www.gotomeet.me/39SerenityPlace/clubhouse"
  ["conference_phone"]=>
  string(10) "8668994679"
  ["conference_phone_notes"]=>
  string(26) "Access Code : 856-476-517#"
  ["types"]=>
  array(4) {
    [0]=>
    string(1) "D"
    [1]=>
    string(1) "O"
    [2]=>
    string(3) "ONL"
    [3]=>
    string(2) "TC"
  }
  ["location"]=>
  string(14) "Serenity Place"
  ["location_url"]=>
  string(53) "https://aa-stlawrenceny.org/locations/serenity-place/"
  ["formatted_address"]=>
  string(38) "175 E Orvis St, Massena, NY 13662, USA"
  ["region_id"]=>
  int(36)
  ["region"]=>
  string(18) "Eastern Ontario 83"
  ["group_id"]=>
  int(2314)
  ["group"]=>
  string(14) "Serenity Place"
  ["website"]=>
  string(32) "https://www.39serenityplace.com/"
  ["email"]=>
  string(29) "clubhouse@39serenityplace.com"
  ["phone"]=>
  string(10) "3152507410"
  ["mailing_address"]=>
  string(35) "175 E. Orivs St, Massena, NY, 13662"
  ["contact_1_name"]=>
  string(9) "Clubhouse"
  ["contact_1_email"]=>
  string(29) "clubhouse@39serenityplace.com"
  ["contact_1_phone"]=>
  string(10) "3152507410"
  ["district"]=>
  string(0) ""
  ["link"]=>
  string(160) "Serenity Place (Open Discussion) Online Meeting"
}

**Comment by lloy0076** [comment] 2021-07-01 02:51
ALL the Serenity Place meetings are causing it.

**Comment by lloy0076** [comment] 2021-07-01 03:02
Right so I've instrumented it with:

```
if (isset($_REQUEST['foo'])) {
    if (!isset($locations[$meeting['location_id']])) {
        $locations[$meeting['location_id']] = array(
            'name' => $meeting['location'],
            'latitude' => $meeting['latitude'] - 0,
            'longitude' => $meeting['longitude'] - 0,
            'url' => $meeting['location_url'], //can't use link here, unfortunately
            'formatted_address' => $meeting['formatted_address'],
            'meetings' => array(),
        );
    }
    if (!isset($meeting['latitude']) && isset($_REQUEST['foo']) && $_REQUEST['foo']==='print') { print "<pre>"; var_dump($meeting); print "</pre>"; }
} else {
    if (!isset($locations[$meeting['location_id']]) && isset($meeting['latitude'])) {
        $locations[$meeting['location_id']] = array(
            'name' => $meeting['location'],
            'latitude' => $meeting['latitude'] - 0,
            'longitude' => $meeting['longitude'] - 0,
            'url' => $meeting['location_url'], //can't use link here, unfortunately
            'formatted_address' => $meeting['formatted_address'],
            'meetings' => array(),
        );
    }

}
```

If you visit it with [http://aa-stlawrenceny.org/meetings/?tsml-day=any&foo=1](http://aa-stlawrenceny.org/meetings/?tsml-day=any&foo=1) you'll trigger the warnings.

If you visit it with [http://aa-stlawrenceny.org/meetings/?tsml-day=any&foo=print](http://aa-stlawrenceny.org/meetings/?tsml-day=any&foo=print) you'll trigger the warnings ***and** you'll get the var_dump.

![image](https://user-images.githubusercontent.com/1174532/124058351-35eff580-d9f7-11eb-80d0-e061b9577eb4.png)

**Comment by lloy0076** [comment] 2021-07-01 03:04
![image](https://user-images.githubusercontent.com/1174532/124058451-65066700-d9f7-11eb-803e-e86c6d72a38c.png)

![image](https://user-images.githubusercontent.com/1174532/124058461-6d5ea200-d9f7-11eb-9d13-7d027f061847.png)

![image](https://user-images.githubusercontent.com/1174532/124058482-76e80a00-d9f7-11eb-8e16-b8fc128d16f9.png)

**Comment by lloy0076** [comment] 2021-07-01 03:05
Serenity Place is definitely at: 175 E Orvis St, Massena, NY 13662, USA - their web-site has that address (see [https://www.39serenityplace.com/](https://www.39serenityplace.com/)).

**Comment by tech2serve** [comment] 2021-07-01 03:07
So I don't know what affect your code mods will have on things, so I suggest removing them and going back to our released code until we can figure out the root cause.

My next suggestion is to go into those meetings and re-enter a portion of the address which will cause the plugin to geocode the address again. 

Were these meetings entered via CSV import or did you type them into the system?

**Comment by lloy0076** [comment] 2021-07-01 03:19
I re-entered a portion of the address and no warnings appear; I suspect something caused the geocode.

The meetings were entered manually into the system and no warnings appeared UNTIL it upgraded to the current plugin version.

That said we **still** would get warnings when longitude and latitude are not set; this is a production system and many people who use the site are not able to understand what a big `Notice: ,...` from PHP is about and conclude the site is not working and contact me about it.

It is relatively common for geocoders to fail for a whole myriad of reasons, ranging from bad setup, the address not actually existing or simply because they can. So, whilst the lack of a longitude and latitude might very well be an issue that needs to be addressed, **I am not sure we should cause PHP level warnings** if they do not exist.

It might be possible to silence the warnings but this would involve adjusting the PHP configuration (which is difficult for me to do - it's on a fairly inexpensive CPanel server but you get what you pay for) or possibly the WordPress configuration (which I suspect might be raising the debug to screen level).

So I think an actual resolution would be to:

- Determine what SHOULD happen if a geocoder fails but there location ID is not set
- Issue a more appropriate warning if that really is an error
- ^^ a more appropriate warning might use WordPress's own logging system or user alert system AS OPPOSED to causing a language level notice

NB. Because I suspect that some people could turn these warnings off, it is possible many/some/everyone else is not seeing this problem.

**Comment by lloy0076** [comment] 2021-07-01 03:23
PS. I've reverted the code MOSTLY back to what it was before.

Specifically it is now:

```
    if (!isset($locations[$meeting['location_id']])) {
        $locations[$meeting['location_id']] = array(
            'name' => $meeting['location'],
            'latitude' => $meeting['latitude'] - 0,
            'longitude' => $meeting['longitude'] - 0,
            'url' => $meeting['location_url'], //can't use link here, unfortunately
            'formatted_address' => $meeting['formatted_address'],
            'meetings' => array(),
        );
    }

    if (!isset($meeting['latitude']) && isset($_REQUEST['foo']) && $_REQUEST['foo']==='print') { print "<pre>"; var_dump($meeting); print "</pre>"; }
```

That last line simply means "if there is no latitude and they've added a `foo` to the request array (by fiddling in the URL for example) and it is the word `print` then var_dump it"; I don't know how well others can read code.

**Comment by tech2serve** [comment] 2021-07-01 22:51
If geocoding fails, the meeting won’t publish. That is the feedback provided to the admin when they’re entering meetings either manually or via an import.

Am I correct that when you re-entered the address, the issue for that meeting resolved?

**Comment by lloy0076** [comment] 2021-07-02 07:37
When I re-entered the address, the issue for *alll* those meetings resolved.

Let's assume that geocoding did not fail - it is sort of possible that the geocoding did pass but didn't (for some reason) fill in the relevant `latitude/longitude` fields.

Alternatively, it did fail and it did publish.

Perhaps it is relevant that I did switch the meetings over from `in person` to `online only` which might have caused the issue (maybe that deleted the `lat/lon`) but if that was the cause it doesn't explain why some (or all) of the other meetings where I made the switch occurred.

**Comment by tech2serve** [comment] 2021-07-02 17:42
Perhaps. Lots of things are possible :-) But, the likelihood of the geocode being completed but a two fields being lost without some error being thrown is really low. 

And your report is the only one and I haven’t seen steps to reproduce, so there isn’t much I can do with this. 

I’m going to close this, but if the issue reoccurs, please let me know and we’ll try to look closer.

**Closed by tech2serve** 2021-07-02 17:42 UTC
Labels: need more information, support/question
