### ISSUE TITLE
Join with Zoom Buttons aren't always working

### ISSUE THREAD

**Issue by nextlevelwebdesign** [code4recovery/12-step-meeting-list#395] opened 2021-06-29 11:54 UTC
**Describe the bug**
The 'Join with Zoom' button on the meeting listing pages are working intemtiently and I'm hoping that you can get them working again?
**To Reproduce**
1:- Got to https://www.ddauk.org/meetings/ and click on a meeting,
2:- Try pressing the 'Join with Zoom' button

**Expected behavior**
50/50% as to whether the button will work or not?

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tech2serve** [comment] 2021-06-29 17:08
Hi @nextlevelwebdesign,

Can you share the exact URL you have in the Conference URL field please?

Have you made changes to your permalinks? It is a bit of a long shot, but please go into Settings --> Permalinks --> Save. Sometimes refreshing these links addresses issues like this.

Sometimes we also see other plugins interfere with javascript functions. For example, I don't know what is providing your Instagram follow link, but perhaps disable it and other plugins (except TSML), reload the page, and then try the Zoom links. If they start working, the issue is probably a conflict.

**Comment by nextlevelwebdesign** [comment] 2021-06-29 19:19
Hi

It’s sometimes works and sometimes doesn’t. But people keep struggling to get it to work and I can’t check all of the meeting buttons every day.

Nut, I’ve also started getting this error:



Kind Regards,
Jon

From: Tech2Serve ***@***.***>
Date: Tuesday, 29 June 2021 at 18:08
To: code4recovery/12-step-meeting-list ***@***.***>
Cc: Next Level Web Design CIC ***@***.***>, Mention ***@***.***>
Subject: Re: [code4recovery/12-step-meeting-list] Join with Zoom Buttons aren't always working (#395)

Hi @nextlevelwebdesign<https://github.com/nextlevelwebdesign>,

Can you share the exact URL you have in the Conference URL field please?

Have you made changes to your permalinks? It is a bit of a long shot, but please go into Settings --> Permalinks --> Save. Sometimes refreshing these links addresses issues like this.

Sometimes we also see other plugins interfere with javascript functions. For example, I don't know what is providing your Instagram follow link, but perhaps disable it and other plugins (except TSML), reload the page, and then try the Zoom links. If they start working, the issue is probably a conflict.

**Comment by nextlevelwebdesign** [comment] 2021-06-29 19:20
Sorry, accidentally sent the email. This is the error in the meeting listing’s backend:

Warning: array_diff(): Expected parameter 1 to be an array, null given in /home/customer/www/ddauk.org/public_html/wp-content/plugins/12-step-meeting-list/includes/functions.php on line 1131

Warning: array_values() expects parameter 1 to be array, null given in /home/customer/www/ddauk.org/public_html/wp-content/plugins/12-step-meeting-list/includes/functions.php on line 1131


Kind regards,

Jon

From: Tech2Serve ***@***.***>
Date: Tuesday, 29 June 2021 at 18:08
To: code4recovery/12-step-meeting-list ***@***.***>
Cc: Next Level Web Design CIC ***@***.***>, Mention ***@***.***>
Subject: Re: [code4recovery/12-step-meeting-list] Join with Zoom Buttons aren't always working (#395)

Hi @nextlevelwebdesign<https://github.com/nextlevelwebdesign>,

Can you share the exact URL you have in the Conference URL field please?

Have you made changes to your permalinks? It is a bit of a long shot, but please go into Settings --> Permalinks --> Save. Sometimes refreshing these links addresses issues like this.

Sometimes we also see other plugins interfere with javascript functions. For example, I don't know what is providing your Instagram follow link, but perhaps disable it and other plugins (except TSML), reload the page, and then try the Zoom links. If they start working, the issue is probably a conflict.

**Comment by tech2serve** [comment] 2021-06-29 19:24
Don’t worry about that warning right now.

You didn’t provide the URL you’re using for the meetings (you can obfuscate the ID and password if you wish).

I also provided two tests to see see if the issue cleared up, but your reply doesn’t indicate you tried those. Please advise.

**Comment by nextlevelwebdesign** [comment] 2021-06-29 19:46
Hi

https://www.ddauk.org

Jon

**Comment by tech2serve** [comment] 2021-06-29 19:49
For the Zoom meeting.

**Comment by nextlevelwebdesign** [comment] 2021-06-29 19:51
Hi

Thought I’d said that there isn’t any particular url at the moment; when I
tested them, they all worked. But, they don’t always work.

I’m just restarting my computer and then I’ll run the tests you requested.

Jon

**Comment by tech2serve** [comment] 2021-06-29 19:58
Ahhh. I think we've been talking past each other for this particular Q.

On your admin side, in the meeting edit page, I'm looking or an example of what you're entering in the Conference URL field. I'm just curious if there is something particular with the URL. Here is an example:

<img width="786" alt="image" src="https://user-images.githubusercontent.com/31904316/123859510-97ba3d80-d8d9-11eb-8cf2-9309ba3fe9c2.png">

**Comment by nextlevelwebdesign** [comment] 2021-06-29 20:30
Hi

I had to create this page with all of the links on it so you can see for yourself:
https://www.ddauk.org/meetings-listed-all/

Jon

From: Tech2Serve ***@***.***>
Date: Tuesday, 29 June 2021 at 20:58
To: code4recovery/12-step-meeting-list ***@***.***>
Cc: Next Level Web Design CIC ***@***.***>, Mention ***@***.***>
Subject: Re: [code4recovery/12-step-meeting-list] Join with Zoom Buttons aren't always working (#395)

Ahhh. I think we've been talking past each other for this particular Q.

On your admin side, in the meeting edit page, I'm looking or an example of what you're entering in the Conference URL field. I'm just curious if there is something particular with the URL. Here is an example:

[image]<https://user-images.githubusercontent.com/31904316/123859510-97ba3d80-d8d9-11eb-8cf2-9309ba3fe9c2.png>

**Comment by 97eighty** [comment] 2021-06-29 21:21
> Warning: array_diff(): Expected parameter 1 to be an array, null given in /home/customer/www/ddauk.org/public_html/wp-content/plugins/12-step-meeting-list/includes/functions.php on line 1131


Which version of PHP are you using?

**Comment by tech2serve** [comment] 2021-06-29 21:40
> Hi I had to create this page with all of the links on it so you can see for yourself: https://www.ddauk.org/meetings-listed-all/ Jon From: Tech2Serve ***@***.***>

That page is not related to TSML. 

You’ve got some things to test and report back on from above. Feel free to report back those results.

**Comment by nextlevelwebdesign** [comment] 2021-06-30 07:35
That’s a list of all of the Zoom links that you wanted to look at?

RE: tests, the buttons are all working today, so there is little point in trying to fix something that isn’t broken at the moment? I did save the permalinks again though…

Kind Regards,
Jon


From: Tech2Serve ***@***.***>
Date: Tuesday, 29 June 2021 at 22:40
To: code4recovery/12-step-meeting-list ***@***.***>
Cc: Next Level Web Design CIC ***@***.***>, Mention ***@***.***>
Subject: Re: [code4recovery/12-step-meeting-list] Join with Zoom Buttons aren't always working (#395)

Hi I had to create this page with all of the links on it so you can see for yourself: https://www.ddauk.org/meetings-listed-all/ Jon From: Tech2Serve @.***>

That page is not related to TSML.

You’ve got some things to test and report back on from above. Feel free to report back those results.

**Comment by nextlevelwebdesign** [comment] 2021-06-30 09:38
PHP 7.4.20

Jon

From: 97eighty ***@***.***>
Date: Tuesday, 29 June 2021 at 22:21
To: code4recovery/12-step-meeting-list ***@***.***>
Cc: Next Level Web Design CIC ***@***.***>, Mention ***@***.***>
Subject: Re: [code4recovery/12-step-meeting-list] Join with Zoom Buttons aren't always working (#395)

Warning: array_diff(): Expected parameter 1 to be an array, null given in /home/customer/www/ddauk.org/public_html/wp-content/plugins/12-step-meeting-list/includes/functions.php on line 1131

Which version of PHP are you using?

**Comment by tech2serve** [comment] 2021-06-30 14:20
Hi Jon,

> That’s a list of all of the Zoom links that you wanted to look at? 

I was specifically asking to see an example of how the meeting is entered on the backend in the admin edit page (as in the example I showed in the image) because we’ve had people try to put some strange things in that field, so it is one of the things I try to rule out. Seeing the Zoom links on an entirely different page doesn’t tell me what is in the database or being interacted with by the JavaScript when the button is clicked.

In my experience, JavaScript in Wordpress can easily experience conflicts from other plugins or customizations the admin has made.  This is why we usually ask admins to disable other plugins  and remove customizations when troubleshooting these types of issues. So if the issue reoccurs, please start with this step.

@97eighty is another of our members, and I’m glad he asked about PHP. We’re seeing some increased reports that PHP 7.4 might be creating problems. We don’t know why yet, so being able to confirm this is the source would be helpful to us.

All that said, if the links are working now, refreshing permalinks *might* have solved the issue. I’d like to see them continue working for a few days before we close the ticket though. 

-Tim

**Comment by nextlevelwebdesign** [comment] 2021-06-30 19:44
Hi

This link didn’t work on Monday?:

[Graphical user interface, text, application, email  Description automatically generated]

From: Tech2Serve ***@***.***>
Date: Wednesday, 30 June 2021 at 15:21
To: code4recovery/12-step-meeting-list ***@***.***>
Cc: Next Level Web Design CIC ***@***.***>, Mention ***@***.***>
Subject: Re: [code4recovery/12-step-meeting-list] Join with Zoom Buttons aren't always working (#395)

Hi Jon,

That’s a list of all of the Zoom links that you wanted to look at?

I was specifically asking to see an example of how the meeting is entered on the backend in the admin edit page (as in the example I showed in the image) because we’ve had people try to put some strange things in that field, so it is one of the things I try to rule out. Seeing the Zoom links on an entirely different page doesn’t tell me what is in the database or being interacted with by the JavaScript when the button is clicked.

In my experience, JavaScript in Wordpress can easily experience conflicts from other plugins or customizations the admin has made. This is why we usually ask admins to disable other plugins and remove customizations when troubleshooting these types of issues. So if the issue reoccurs, please start with this step.

@97eighty<https://github.com/97eighty> is another of our members, and I’m glad he asked about PHP. We’re seeing some increased reports that PHP 7.4 might be creating problems. We don’t know why yet, so being able to confirm this is the source would be helpful to us.

All that said, if the links are working now, refreshing permalinks might have solved the issue. I’d like to see them continue working for a few days before we close the ticket though.

-Tim

**Comment by tech2serve** [comment] 2021-07-03 00:29
Hi Jon--

The latest release should address the PHP warnings you were getting.

I just checked your listings and found the Zoom links seem to be working okay. 

I'm going to close this issue, but if you still find you're having trouble with Zoom links, please let us know.

**Closed by tech2serve** 2021-07-03 00:29 UTC
Labels: need more information, support/question
