### ISSUE TITLE
Update/Publish button grays out on certain addresses

### ISSUE THREAD

**Issue by WoodieFL** [code4recovery/12-step-meeting-list#195] opened 2020-10-23 15:16 UTC
**Describe the bug**
When I enter certain addresses, the Update button grays out so I cannot update the meeting. This also happens if I try to add a new meeting. I typed them into Google Maps directly and it did not have a problem with it. Two addresses are listed below.

5609 US-19, New Port Richey, FL, 34652, USA
5024 Trouble Creek Rd, New Port Richey, FL, 34652, USA

**To Reproduce**
Go to aapasco.org/wp-admin, sign on
Click on Meetings
Click on Add New
Enter information for new meeting (anything will do)
Scroll down to the address
Type in "5024 Trouble Creek Rd, New Port Richey, FL, 34652, USA" and tab out of the field
Scroll up to Publish button and it is grayed out.

**Expected behavior**
I expected to be able to click on the Publish button to add this meeting!

**Screenshots**
![Sober Landings - good](https://user-images.githubusercontent.com/73310072/97020451-90a78800-151f-11eb-99ac-957f04251f0e.PNG)
![Sober Landings - bad2](https://user-images.githubusercontent.com/73310072/97020453-91401e80-151f-11eb-993e-a912ba8784e4.PNG)
![Sober Landings - bad](https://user-images.githubusercontent.com/73310072/97020454-91d8b500-151f-11eb-9c27-5ab7421a59f7.PNG)
![Sober Landings - good2](https://user-images.githubusercontent.com/73310072/97020456-91d8b500-151f-11eb-9b0e-cea685415190.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser Microsoft Edge
 - Version 86.0.622.48 (Official build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
This happens on another address when I try to change it to the correct address:
1733 US-19 Alt, Tarpon Springs, FL, 34689, USA changes to
1733 US-19, Holiday, FL, 34691, USA  which is incorrect and does not have the correct map location either. It will still show the Region as Tarpon Springs.
Again, Google Maps shows and find the correct address.
![Google Maps 1733 US-19](https://user-images.githubusercontent.com/73310072/97021651-1d9f1100-1521-11eb-9e38-0331a6f66409.PNG)
![Meeting App 1733 US-19](https://user-images.githubusercontent.com/73310072/97021652-1e37a780-1521-11eb-894c-91e3bc382f1e.PNG)

**Comment by tech2serve** [comment] 2020-10-23 17:46
Let's start with the first two addresses. I'm not experiencing the same issue on my dev site, so we need to see if we're getting an error or some other indication on your site.

I'm not familiar with Microsoft Edge so you may have to do some research. Please figure out how to open a developer console in your browser, and then try entering the address again.. This should let you monitor for any errors being thrown. 

Also, what version of TSML are you using?

**Comment by WoodieFL** [comment] 2020-10-24 17:08
I opened the developer console and traced through the code but it does not
create an error message, it just disables the Publish button. I'm not
familiar enough with JavaScript to really debug it and was hoping you could
go on my site to see it happen.

We're running version 3.8.0 of TSML and WordPress 5.5.1. I see this message
when I click on "View Details":

[image: image.png]

Woodie Sayles
(727) 642-5372
woodiefl@gmail.com  =^..^=

[image: ❤][image: ][image: ] (Love, happiness, cats)

**Comment by tech2serve** [comment] 2020-10-24 18:21
I'm stumped, so I'm going to take some stabs in the dark and see if we get lucky.

Do you have any restrictions on your API key? I do see you're using Google maps; admittedly, if you did have restrictions, you would not be expected to see the map display, so I doubt this is the issue.

Have you tried another browser? Say, Firefox? If so, does the issue persist? 

Does your host provider give you access to a cpanel or similar set of controls that allow you to clear the cache for the website? A surprising number of inexplicable issues have been cleared up by this action.

Please try deactivating and reactivating the plugin. Don't delete it though (or you'll lose your meeting data), and please make sure you have good backups of your data.

If none of this helps, I have another step we can take as a test that is a bit more complicated. We'll discuss that if needed.

BTW, your image.png for "View Details" didn't come through. Where is the "View Details" button to which you're referring?

**Comment by joshreisner** [comment] 2020-10-25 14:53
The background on this button-graying-out logic: when an address is changed the button is briefly grayed out, when the response comes back from Google with latitude, longitude, and formatted address, it's un-greyed-out. This is so you don't accidentally change the address but not the pin or have an unformatted address.

An un-google-able address could theoretically cause this, but more likely are the scenarios Tech2Serve intuited (3rd party javascript issue or API key issue). Geocoding uses our API key.

I'm able to get this address to work on my test site without problems, so I'm stumped too!

![Screen Shot 2020-10-25 at 8 44 42 AM](https://user-images.githubusercontent.com/1551689/97110501-4a793280-169f-11eb-871a-c14cee39688b.png)

**Comment by WoodieFL** [comment] 2020-10-25 15:01
I'm stumped as well! I've tried everything I can think of, but nothing
changes. What's even stranger is that if I only type in part of the address
and tab out of the field, TSML will fill in the address but put the wrong
city. However, the Publish button is still disabled.

When you said to clear the cache, did you mean the browser's cache or the
website cache? I cleared the browser cache, but no change. I looked on my
control panel and didn't see anything to clear the website cache, but I
will contact support and see if they can help with that.

The "View Details" link is on the plugins page. Here is what comes up:

[image: image.png]


Thanks for all your help. Hope we can figure this out.


Woodie Sayles
(727) 642-5372
woodiefl@gmail.com  =^..^=

[image: ❤][image: ][image: ] (Love, happiness, cats)

**Comment by WoodieFL** [comment] 2020-10-25 16:02
Sorry - I didn't answer all your questions.

1. I had MapBox for maps originally and read that it was causing some
problems so I switched to Google Maps. I didn't have any restrictions on
the Google Maps key, but have added some now because of their
recommendations.
2. I've tried Chrome as well as Edge with the same results.
3. Submitted support ticket to see how to clear the website cache.
4. I deactivated the plugin, closed the browser, reopened it, activated the
plugin - no change.

I just had the web host tech clear the website cache, but no change. 😕


Woodie Sayles
(727) 642-5372
woodiefl@gmail.com  =^..^=

**Comment by tech2serve** [comment] 2020-10-25 20:18
Hey @WoodieFL, I'm going to send you an email. Although I don't normally like to take conversations offline, my next idea is something I'd like to handle that way.

**Comment by WoodieFL** [comment] 2020-10-26 13:19
The answers to your questions are yes and yes.

**Comment by WoodieFL** [comment] 2020-10-26 13:23
Could this have anything to do with it? I just saw these on my Dashboard.
![Active PHP session](https://user-images.githubusercontent.com/73310072/97177695-e7ee6800-176c-11eb-90f3-71ce1c407429.PNG)

**Comment by WoodieFL** [comment] 2020-10-26 18:20
I just tried deleting the TSML plugin, reinstalling it, and uploading the meeting list, but there's still no change. I actually think it's just about any address now, but I haven't tested that to be sure. It could be only the ones for New Port Richey. I won't be able to do any debugging until tomorrow or Wednesday unfortunately. For the time being, I'm updating a CSV file and reimporting it with the new data. What's so weird is that that works fine and the address and map are correct.

**Comment by WoodieFL** [comment] 2020-10-27 16:26
Are you still available to help me solve this problem? After double checking, I don't have phpMyAdmin, but I can edit the PHP.ini file and also have file manager which may be able to get to the files you need.

**Comment by WoodieFL** [comment] 2020-10-27 18:51
Oops! Forgot to attach the screen shots.
[aapasco screen shots.pdf](https://github.com/code4recovery/12-step-meeting-list/files/5447441/aapasco.screen.shots.pdf)

**Comment by WoodieFL** [comment] 2020-10-28 15:39
I found the problem with finding the tsml_addresses option_name. The table has 650 rows but was only searching in the first 25. Attached is the file you wanted.
[qi2p_options_tsml_addresses.zip](https://github.com/code4recovery/12-step-meeting-list/files/5453047/qi2p_options_tsml_addresses.zip)

**Comment by tech2serve** [comment] 2020-10-28 16:28
Hey @WoodieFL 

I need the data as a JSON file, please. The steps I sent you via email should work. Please let me know if you need me to recap them.

**Comment by WoodieFL** [comment] 2020-10-28 16:56
Sorry - I got so excited finally finding the tsml_addresses option that I didn't finish reading your instructions. :-( Here is the JSON file.
[qi2p_options-tsml_addresses-JSON.zip](https://github.com/code4recovery/12-step-meeting-list/files/5453571/qi2p_options-tsml_addresses-JSON.zip)

**Comment by WoodieFL** [comment] 2020-10-29 13:45
Here is the "pretty" JSON file.
[qi2p_options_tsml_addresses_pretty-JSON.zip](https://github.com/code4recovery/12-step-meeting-list/files/5458714/qi2p_options_tsml_addresses_pretty-JSON.zip)

**Comment by WoodieFL** [comment] 2020-10-30 15:07
I understand. One question before I do your last instruction - I noticed that the tsml_addresses table has NO for autoload, where all the other tables have YES. Should I change it and try entering an address before doing what you suggested?

**Comment by tech2serve** [comment] 2020-10-30 15:14
I noticed that as well, and it is a possibility. I'm unclear how it got changed as most other databases I've looked at, it is set to autoload. 

In short, it would not hurt to try it.

**Comment by WoodieFL** [comment] 2020-11-02 15:47
I just n1oticed something - the website is in a subdirectory of the root. Could this be causing the problem?

**Comment by tech2serve** [comment] 2020-11-02 15:52
I doubt it. Are you still not able to to update after performing the "last instruction"?

**Comment by tech2serve** [comment] 2020-11-02 16:14
@WoodieFL,

Sometimes I forget to whom I've suggested particular trouble shooting steps. And I just realized that we have not adequately run down the potential for third party interference. If you have a staging site, install only TSML on it, and then try adding the meetings there. If it works, then start adding your other plugins in until it stops working.

Alternatively, deactivate all the other plugins on your regular site and see if the problem resolves.

Does your hosting

**Comment by WoodieFL** [comment] 2020-11-02 16:56
I think I've tried that, but I will do it again to be sure.

**Comment by WoodieFL** [comment] 2020-11-02 18:08
I am running version 3.9.3 of TSML and version 5.5.3 of WordPress. When I click on the "View Details" link from the TSML plugin, I get the attached message.
![View Details page](https://user-images.githubusercontent.com/73310072/97897782-fad0e180-1d04-11eb-840a-dc7565314d64.PNG)

**Comment by tech2serve** [comment] 2020-11-02 20:34
I wouldn't worry too much about that message right now. It basically means we haven't bumped the "Compatible up to" version yet. In reality, the only thing we're still working through is the the use of a deprecated function by one of our dependencies. Very likely unrelated.

I see you closed the ticket. I hope that means you got something figured out. Still happy to help if needed.

**Comment by WoodieFL** [comment] 2020-11-02 22:56
Oh no! I didn't mean to close the ticket. I don't even know how to do that.

**Comment by tech2serve** [comment] 2020-11-02 23:28
@WoodieFL,

Please install the Enable jQuery Migrate Helper plugin created by the Wordpress Team. You can get this by:

1. On your Admin screen, click on Plugins.
1. Click on Add New.
1. In the search field, type "Enable jQuery Migrate Helper".

    <img width="1272" alt="image" src="https://user-images.githubusercontent.com/31904316/97930046-38972f80-1d30-11eb-82dc-8eb9fee3d55a.png">

1. Install and activate. 

You may see some warnings show up on your meeting edit page. If not, please let me know.

Then run your tests again. We've starting to see more sites resolve similar issues with this addition plugin active.

**Comment by WoodieFL** [comment] 2020-11-03 00:16
OMG!! It worked! Should I leave it the way it is with the warnings at the top?

**Comment by tech2serve** [comment] 2020-11-03 00:35
Yes.

We don't know yet for sure if the problem actually in our plugin or if the issue is coming from a third party plugin you have. 

If you see warnings come up related to other plugins, please explore those with that developer.

If you don't have any other issues, please close this Issue now.

**Closed** 2020-11-03 01:08 UTC
Labels: support/question
