### ISSUE TITLE
Testing Beta Version 3.9.0b - jQuery Migrate Helper — Warnings encountered

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/12-step-meeting-list#194] opened 2020-10-21 00:05 UTC
**Describe the bug**
This TSML plugin version produces 3 instead of 4 error warnings found in previous versions.

This page generated the following warnings:

1. /wp-content/plugins/12-step-meeting-list-develop/assets/js/admin.min.js: jQuery.parseJSON requires a valid JSON string
2. /wp-content/plugins/12-step-meeting-list-develop/assets/js/admin.min.js: jQuery.parseJSON requires a valid JSON string
3. /wp-content/plugins/12-step-meeting-list-develop/assets/js/admin.min.js: jQuery.parseJSON requires a valid JSON string

This occurs when either editing a meeting or adding a new one.

WordPress v.5.5.1
All Browser versions.
Win 10

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tech2serve** [comment] 2020-10-21 00:08
Anything different from #168 ?

**Comment by Grateful-Viv** [comment] 2020-10-21 00:19
My bad. v3.7.2. had 4 lines which changed with v3.8.0. What was no longer in 3.8.0 and 3.9.0b is this line:

/wp-content/plugins/12-step-meeting-list/assets/js/admin.min.js: jQuery.fn.size() is deprecated; use the .length property

**Comment by tech2serve** [comment] 2020-10-21 00:22
Ok. I'm gonna close this as a duplicate. I don't believe any of this is directly related to the 3.9.0 release. We need to scrub jQuery throughout TSML.

Duplicate of $168

**Closed by tech2serve** 2020-10-21 00:22 UTC
