### ISSUE TITLE
JSON import performance degraded 

### ISSUE THREAD

**Issue by mpgeek** [code4recovery/12-step-meeting-list#311] opened 2021-04-07 14:56 UTC
I'm not certain this is a bug.

I run a JSON import from a remote source every day. For the last few months, up to about a month ago, the import process would complete in just a few minutes. Over 1000 meetings would come in error free. I ran this every night. At some point recently this process now takes hours and it seems to batch the import into sets of 25 meetings, and hangs in between sets.

I'm wondering about the implementation of the JSON import. Did something change such that data import is now batched? Did it move to cron-type scheduling? I'm also not convinced my hosting (Siteground) is not somehow interfering. I'm hoping a contributor can shed light on whether or not the implementation changed in a recent update.

**Comment by tech2serve** [comment] 2021-04-07 15:30
Hi @mpgeek,

Let's start by some additional information:

1. What is your site address? 
1. Where are you importing from? 
1. Have you changed the geocoding option from Legacy to the beta API gateway?
1. Are you seeing any errors in the debug/developer console (you'll need to open it for your specific browser)?

Nothing of significance has changed unless you're using the beta API gateway. However, since only meetings with changed/new addresses should be geocoded, I suspect this is not the issue. But, I'd like to rule it out. Oh, I should add that an exception might exist, and we should probably rule that out as well.

For background, the import process is done in two stages. First, all the data in ingested and sanitized before being stored in a temporary buffer. That buffer is then parsed in batches of 25 to update your meeting list. In that sense, what you're seeing there is correct. 

As you can imagine, this process is very database intensive, and so I also think it is reasonable for you to investigate database loading with Siteground.

**Comment by mpgeek** [comment] 2021-04-07 16:13
My site is at https://www.greshamaa.org/, and importing from https://www.pdxaa.org/wp-admin/admin-ajax.php?action=meetings. The idea is that our meeting data is managed from the larger site and our local site just pre-filters to our region. One data set, many views.

We're using the Legacy geocoding option; i have never changed that IIRC.

The console is revealing something interesting, though. I'm seeing a 524 error on https://www.greshamaa.org/wp-admin/admin-ajax.php?action=tsml_import, 
![Screen Shot 2021-04-07 at 9 07 05 AM](https://user-images.githubusercontent.com/1072643/113899092-4f2f3000-9781-11eb-80c3-d20dbd953151.png)

Which originates from Cloudflare. 
![Screen Shot 2021-04-07 at 9 08 07 AM](https://user-images.githubusercontent.com/1072643/113899148-5c4c1f00-9781-11eb-8269-65efa8f05341.png)

This looks like timeout. I'm wondering now if this is processing delay and Clouldfare times out. I think that can be arranged if we think the plugin is operating as expected.

**Comment by tech2serve** [comment] 2021-04-07 17:11
> My site is at https://www.greshamaa.org/, and importing from https://www.pdxaa.org/wp-admin/admin-ajax.php?action=meetings. The idea is that our meeting data is managed from the larger site and our local site just pre-filters to our region. One data set, many views.

Interesting approach, and one I would not typically suggest to people. We normally like to see smaller groups manage their data and feed it to the higher level site that then feeds it to Meeting Guide. Or have the smaller groups report to Meeting Guide and provide a feed to the higher level that only aggregates (but doesn't report). (That does create other issues though, typically for outlying areas).

All that said, I don't have any real performance data to back up this claim, but I am not personally convinced Wordpress is optimized for imports of large amounts of data. 
> 
> We're using the Legacy geocoding option; i have never changed that IIRC.

If you're willing to switch to the Beta API Gateway, and run the import, that will let me check our logs and confirm the issue is not a bunch of unnecessary geocodes. Those would slow things down (and would probably represent a bug).

Do you know what version of TSML Portland is using?

> 
> The console is revealing something interesting, though. I'm seeing a 524 error on https://www.greshamaa.org/wp-admin/admin-ajax.php?action=tsml_import,
> ![Screen Shot 2021-04-07 at 9 07 05 AM](https://user-images.githubusercontent.com/1072643/113899092-4f2f3000-9781-11eb-80c3-d20dbd953151.png)
> 
> Which originates from Cloudflare.
> ![Screen Shot 2021-04-07 at 9 08 07 AM](https://user-images.githubusercontent.com/1072643/113899148-5c4c1f00-9781-11eb-8269-65efa8f05341.png)
> 
> This looks like timeout. I'm wondering now if this is processing delay and Clouldfare times out.
> 
> Is there a best practice around TSML (or even wordpress to facilitate import) configuration when Cloudflare is in play?

None that I'm aware of related specifically to Cloudfare. 

I'm aware of others who will experience long import times with large data sets like yours. I'm not sure there is a good answer as I suspect the real issue is either the database loading limits the hosting providers puts in place or Wordpress' design. I do admit though I cannot be certain of this. But if you're not seeing errors from TSML, the problem is likely not with the plugin (other than a lack of optimization with that as well).

As I said above, my preferred architecture is for districts to feed information to Intergroups (or Areas as appropriate) because it spreads the workload and *usually* results in more accurate meeting data. 

If you're willing to test the API Gateway, please note the time you start the import and let me know. I'll check our logs.

**Comment by mpgeek** [comment] 2021-04-12 23:16
Thanks for the detailed reply. Your point on groups managing their own data then feeding up to larger entities is well-taken. We have some political navigation to do in order to implement the model you suggest. I like it a lot, but it will be a bit before we can get there.

I agree with your points on host bottlenecks, database load and WP itself not really being a high-performance import platform, so i guess i'm going to have to work with what i can squeeze out for now. Disabling Cloudflare and running refresh gave me at least a reasonable update time, i got all the meetings in under an hour. I can do some page rules in Cloudflare to fix that up, and I can report back here how that works out if that's of interest.

But for now, just to make sure there's nothing weird going on, i switched to the BETA API Gateway geocoding method and kicked off a fresh re-import from JSON feed at April 12, 2021 3:38 pm (PDT). If you see anything interesting in the logs, it would be swell to know about that.

**Comment by tech2serve** [comment] 2021-04-13 01:42
Hi @mpgeek--

I'm glad disabling Cloudfare improved things. At least you have something you can work from.

I only saw three queries from your site and none seemed to be a problem. 

So I imported the Portland feed into my dev site on my laptop and it only took a few minutes. I did see this error, but that is the only issue:

<img width="409" alt="image" src="https://user-images.githubusercontent.com/31904316/114484087-941af280-9bd7-11eb-95a6-4c3d9bb1df88.png">

You might also consider discussing this issue with you hosting provider.

**Comment by mpgeek** [comment] 2021-04-13 15:02
Interesting. Thanks for looking. Do you recommend staying with the beta geocode API, or moving back to legacy?

**Comment by tech2serve** [comment] 2021-04-13 15:47
If the beta geocode API is working for you, stay with it if you're willing. That gives us more test data regarding performance. Over the coming months, we'll roll out upgrades to that, and eventually make that the permanent solution. 

I am going to close this issue as I don't think we're seeing anything that shows the problem is with TSML. If that changes, we can reopen the issue down the road.

And, if you do learn more about the real cause, or how tweaking Cloudfare further improves things for you, please do come back and post your lessons.

Thanks!

**Closed by tech2serve** 2021-04-13 15:47 UTC
Labels: support/question
