### ISSUE TITLE
Trying to change Meeting locations

### ISSUE THREAD

**Issue by indelg1** [code4recovery/12-step-meeting-list#213] opened 2020-11-07 02:48 UTC
For some reason, if I change a meeting location in one meeting, it makes the same changes in several meetings.  Even though I do not have checked the feature that says change for all meetings in the same location.

I have several meeting I need to have different regions and locations.  But everyone time I change one meeting, it changes the other meeting as well.  I am not sure what to do to stop this.

Any help appreciated.

Greg

**Comment by tech2serve** [comment] 2020-11-07 02:50
Please complete as much of this as possible. 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by indelg1** [comment] 2020-11-07 03:04
I am running the 12-Step Meeting list on my website www.sca-recovery.org.  My website runs on WordPress 5.5.3.   I am trying to add ZOOM meetings and Telephone meetings.  It forces me to put in an address (of which I do not have one because they are virtual); however, we put in New York, NY for them all.    I am trying to make the edits within WordPress Admin, on a Windows 10 machine and Chrome.   This is an admin issue because I am trying to make edits on the back-end.  Users do not experience any issues other than seeing incorrect information because I cannot seem to edit records individually.  Every change seems to be global based on the Address field.

When I try and change the location and region of these Virtual meetings, it makes the change across all of our Telephone and Zoom meetings even though the value should be different.  But if ever I make a change on one virtual meeting, it changes the value in the Region and Location field for all meetings.  I am not sure why this is happening and why I cannot get each record to take individual edits.  Please help.  This is messing up the records in my database.

**Comment by indelg1** [comment] 2020-11-07 03:45
What seems to be happening, for the Virtual meetings we have designated the address as New York, NY.  But the Zoom location is actually different on many of them, for example, Zoom room #1, Zoom Room #2 etc.  What seems to happen is when I change the location and region for one Zoom meeting, it changes those fields in other records that have the same address designation of New York, NY.  Since all of our new Virtual meetings have that Address designation, this is a problem.  We also have phone meetings that we have given the address of New York, New York and that is a problem as well.  It all seems to link back to Address.  As long as the address field is identical, it makes the change.  Since we have no real address for our virtual meetings, then a change to one meeting seems to take effect on all other meetings with that address.  Please help!

**Comment by tech2serve** [comment] 2020-11-07 18:26
I *think* I understand and will try to duplicate.

Screen shots may be helpful.

**Comment by tech2serve** [comment] 2020-11-07 19:06
> When I try and change the location and region of these Virtual meetings, it makes the change across all of our Telephone and Zoom meetings even though the value should be different. But if ever I make a change on one virtual meeting, it changes the value in the Region and Location field for all meetings. I am not sure why this is happening and why I cannot get each record to take individual edits. Please help. This is messing up the records in my database.

Online meetings are indeed tied to a location (approximate) with the intention being that the responsible service entity is defined by the geographical location. 

I'm not clear on what value you think should be different regarding the location. 

I just tested with two online meetings associated with the same city, state location. I then:

1) Edited Online Meeting 2 meeting types by add Big Big.
2) Clicked "Update" for Online Meeting 2.
3) Navigated to Online Meeting 1.
4) Confirmed Online Meeting 1 *does not* have Big Big checked as a type.
5) Confirmed Online Meeting 1 retained its unique Zoom link.

I repeated this test by:
1) Edited Zoom Link for Online Meeting 1
2) Clicked "Update" for Online Meeting 1
3) Navigated to Online Meeting 2.
4) Confirmed Online Meeting 2 still have Big Book checked.
5) Confirmed Online Meeting 2 retained its unique Zoom link.

If this is not what you're experiencing, please provide the exact steps necessary to reproduce the behavior using the form I've provided. I've found that trying to guess what the user is seeing does not lead to success :-).

I'll also point out that locations are intended to be unique. This means the values for Location and Address do (and should) depend on each other, and both have to do with geography. I hope this makes sense, and would be seen as expected behavior. We would not want to have a Location (e.g., Cavalry Methodist Church) have two different addresses. If you're trying to use Location to represent a particular Zoom meeting room, the plugin isn't designed to do that. You'll either need to enter different meetings for each of those, or explain the different room numbers in the meeting notes.

I hope that helps. Let me know.

Thanks.

**Comment by indelg1** [comment] 2020-11-07 20:00
The issue is that we defined several of our telephone meetings with the Address of New York, NY, again no real address is needed.  

The region for telephone meetings is TEL.  We used the same address (New York, NY) for some of our Virtual meetings.  We changed the region value to 'Virtual' for the virtual meetings.  This also went ahead and changed the region for the 'Tel' meetings to "Virtual'.  We select and create our lists based on that region value so now the telephone meetings (TEL) are falling under 'Virtual'   

I think I understand why this has happened now, but I had no idea it would.  It's created an issue.  It seems not only that I need to put in a fake address for these Telephone and Virtual meetings, but they need to be unique as well???  Any ideas of a better way to avoid this issue?  You see the issue is that for Telephone and Virtual meetings, the Address is really not a relevant piece of information.   People from all over the country can and do attend those meetings from wherever they are.  Thank you...

**Comment by tech2serve** [comment] 2020-11-07 20:23
I think if you use the fields as they are designed to be used, you'll be fine. TEL is not a region. Bronx might be considered a region. Ditto with "Virtual". It isn't a region. You might be able to get it to work, or you might continue to experience troubles. The Regions and Districts do allow you to be a bit creative, but as you learned if you try to apply that too far down into Location, it can lead to troubles. Location and Addresses are tightly coupled.

And all meetings do require an address/location, but the address can now be approximate as of v3.9.0. The intention is to ensure all meetings can be somehow associated with their service entity (region or district). In future releases, we expect to add more support fo characterizing meeting by their attendance options which will help.

I'm going to close this as I believe your issues are understood and that if you stick with a context of geography for locations, you should be okay with the database.

**Closed by tech2serve** 2020-11-07 20:23 UTC
Labels: need more information
