### ISSUE TITLE
[Bug]: 12 Step Meeting PDF Generator Broken as a result of recent changes in TSML

### ISSUE THREAD

**Issue by marcinyorkpa** [code4recovery/12-step-meeting-list#546] opened 2021-10-03 23:44 UTC
### Contact Details

webmaster@york-pa-aa.org

### Website With Issue

https://york-pa-aa.org

### What happened?

We use the "12 Step Meeting PDF Generator" WordPress plugin, from https://github.com/cdtoews/12-step-meeting-pdf, that works in concert with the 12 Step Meeting List.

Starting sometime recently, that PDF Generator plugin began throwing this error:

```
 Fatal error: Uncaught Error: Call to undefined function tsml_define_strings()
in /hermes/bosnaweb23a/b2708/ipg.yaiweb/york-pa-aa/york-pa-aa/wp-content/plugins/12-step-meeting-pdf-generator/includes/admin-gen.php on line 209

Call stack:

    tsmp_gen_page()
    wp-includes/class-wp-hook.php:303
    WP_Hook::apply_filters()
    wp-includes/class-wp-hook.php:327
    WP_Hook::do_action()
    wp-includes/plugin.php:470
    do_action()
    wp-admin/admin.php:259
    require_once()
    wp-admin/edit.php:10
```

I realize that another plugin breaking isn't your problem... but it looks like that plugin isn't actively being worked on, and it looks like it is tightly coupled to the `tsml_define_strings()` function in the TSML.

Do you have any advice on how to get help with this? I'm not sure what the relationship is between the PDF Generator Plugin and TSML, but perhaps if you know each other and talk, y'all could see if you could fix this? If not, I'll see if I can figure out how to get support for that plugin.

Thanks!!!

### TSML Version

Latest (default)

### Wordpress Version

Latest (default)

**Comment by tech2serve** [comment] 2021-10-04 00:18
Please try it now. We had a domain transfer hiccup, and it should be fixed. Please let us know.

**Comment by petermixt** [comment] 2021-10-04 00:40
the "12 Step Meeting PDF Generator" WordPress plugin -- the current menu returns:  Error thrown
Call to undefined function tsml_define_strings()

Is this caused by updates to your 12 Step Meeting List?

**Comment by tech2serve** [comment] 2021-10-04 00:44
I don't know yet. The first issue was due to a domain settings goof on our part.

Please look in the dev console and post the complete error here.

Thanks.

**Comment by tech2serve** [comment] 2021-10-04 00:49
@marcinyorkpa I'm transferring this to a Discussion.

**Closed** 2021-10-04 00:49 UTC
Labels: bug
