### ISSUE TITLE
Search results not returning intermittently

### ISSUE THREAD

**Issue by mikepoconnor4** [code4recovery/12-step-meeting-list#280] opened 2021-02-05 18:37 UTC
Sometimes (infrequently) the search does not return results. It happened again this morning, I went to our meeting list and got no results - tried it a few times same thing. Came back about 5-10 minutes later and it was working again.

We have several default searches - they are:

https://oahucentraloffice.com/meetings/?tsml-day=any&tsml-type=ONL
https://oahucentraloffice.com/meetings/?tsml-day=any&tsml-query=(Physical)
https://oahucentraloffice.com/meetings/?tsml-day=any
https://oahucentraloffice.com/meetings/?tsml-day=any&tsml-query=(Hybrid)

None of them worked - and then 5-10 minutes later they all worked.

Has anyone else experienced this? Sorry I can't easily reproduce the issue.

**Comment by tech2serve** [comment] 2021-02-05 21:39
This is not an issue I've heard of before. It might be an issue with the server cache, so you might try clearing that and seeing if the issue goes away.

If you find you can reproduce the issue, especially if it happens repeatedly for a few minutes, open a debugging/developer console with your browser and see if you're getting any errors. And, as always, look at other plugins to see if they're interfering with the pull from your database.

**Comment by mikepoconnor4** [comment] 2021-02-08 18:57
Hi It's happening right now. 

browser console only says this

GET https://oahucentraloffice.com/meetings/?tsml-day=any&tsml-type=ONL 404
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.3.2
DevTools failed to load SourceMap: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/chrome/iframe_handler.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/chrome/content.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/chrome/iframe_handler.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by tech2serve** [comment] 2021-02-08 19:00
I just clicked on the link and the meetings loaded fine in Firefox. 

Try other browsers; clear caches (both server and browser); and disable extensions for Chrome.

**Comment by mikepoconnor4** [comment] 2021-02-08 19:22
Happening now again.

https://oahucentraloffice.com/meetings/?tsml-day=any&tsml-type=ONL

**Comment by mikepoconnor4** [comment] 2021-02-08 19:37
Working again. It seems choppy today - first time I've seen it sporadic in the same day. I don't think the F12 browser console is telling me much - as I get same info about the chrome extensions whether it works or not. The only extra info when it doesn't work is a 404 on the search URL itself. I think I'm going to have look at server logs with one of our other team members.

If you have time, could you try that link a few times through the day - it's failed 2 separate times today so far so maybe you'll encounter same. Sorry to bother you with this - I'm just trying to find any extra info or hints to resolving the issue,

**Comment by tech2serve** [comment] 2021-02-09 14:37
Did you try the steps I suggested?

The 404 error is probably the clue you need: Something is breaking the connectivity between your browser and the server, or the server results are missing. Those are my best guesses at this stage. The former could be caused by a browser extension (Adblock is commonly a cause, or a combination of). The latter would more likely indicate a caching issue. 

If you have other people experiencing the issue, I'd definitely focus on the server. If you're not able to reproduce the issue using Firefox, Safari, etc., then focus on the browser extensions, cache, or other settings.

I'll try to remember to pull your site up a few more times today, but so far I've not experienced the issue.

**Comment by aanecswebmaster** [comment] 2021-02-09 20:25
We are experiencing same symptoms.  Upon a request to "Find A Meeting" we get the meeting finder page, with message "No meetings were found matching the selected criteria."  Problem occurs on multiple computers and browsers.  Changing the search criteria doesn't get anything different.  
See [https://www.aaneok.org/meetings](https://www.aaneok.org/meetings)
We have tried clearing cache on both WP and browsers.
This has been working for some months now, and started  failing today. 
We are at 3.9;6 release of the plugin
One other note.  We have not made the change to functions.php to add our own code for Google mapping.

**Comment by aanecswebmaster** [comment] 2021-02-09 21:00
We made the change to functions.php for our own maps api key.  No help on this problem

**Comment by aanecswebmaster** [comment] 2021-02-10 17:00
Problem is alleviated if not fixed.  For one group the location field had changed from "St. Patrick's Episcopal Church" to "ZOOM ONLY DUE TO WEATHER".  That is when the problem started.  The location address for geocoding did not change.  The problem was alleviated by reversing the change.  Any clues to why that change caused meeting search to fail?

**Comment by mikepoconnor4** [comment] 2021-02-10 17:41
> Did you try the steps I suggested?
> 
> The 404 error is probably the clue you need: Something is breaking the connectivity between your browser and the server, or the server results are missing. Those are my best guesses at this stage. The former could be caused by a browser extension (Adblock is commonly a cause, or a combination of). The latter would more likely indicate a caching issue.
> 
> If you have other people experiencing the issue, I'd definitely focus on the server. If you're not able to reproduce the issue using Firefox, Safari, etc., then focus on the browser extensions, cache, or other settings.
> 
> I'll try to remember to pull your site up a few more times today, but so far I've not experienced the issue.

We'll be looking deeper into the server logs next Monday. I'll let you know what we find.

**Comment by tech2serve** [comment] 2021-02-10 17:44
> Problem is alleviated if not fixed. For one group the location field had changed from "St. Patrick's Episcopal Church" to "ZOOM ONLY DUE TO WEATHER". That is when the problem started. The location address for geocoding did not change. The problem was alleviated by reversing the change. Any clues to why that change caused meeting search to fail?

Did you put that in the Location field, or the Address field? If the latter, geocoding would indeed fail, and the meeting would not longer be published.

**Comment by tech2serve** [comment] 2021-02-10 17:50
> We'll be looking deeper into the server logs next Monday. I'll let you know what we find.

Please keep us posted. I'm not entirely clear @aanecswebmaster is actually having the same issue, but if you made some address/location changes similar to those described in their comment, you might poke into that.

I have opened your meeting list several times over the past two days and have not experienced an issue.

**Comment by mikepoconnor4** [comment] 2021-02-10 18:58
> > We'll be looking deeper into the server logs next Monday. I'll let you know what we find.
> 
> Please keep us posted. I'm not entirely clear @aanecswebmaster is actually having the same issue, but if you made some address/location changes similar to those described in their comment, you might poke into that.
> 
> I have opened your meeting list several times over the past two days and have not experienced an issue.

I agree that @aanecswebmaster seems like a different issue. That bad geocoding seemed like it took down their search altogether - ours seems to be an intermittent server issue. 

And thanks for checking in - the couple of times it happened to us the last week seemed to be in the morning - around 7 am to 10 am HST. Not sure if the time is connected somehow.

**Comment by aanecswebmaster** [comment] 2021-02-11 16:12
Well, after gathering more information, you can forget the connection with changing the Location field (not the address field).  Turns out the problem began some hours after the location change.  It went away about the same time as location change was reversed.  So  it seems we too have an intermittent problem.  I discuss that in a separate post to follow.

**Comment by aanecswebmaster** [comment] 2021-02-11 16:29
On Tuesday, morning our meetings page, https://aaneok.org/meetings/ started failing.   Instead of returning the expected list of meetings, it showed only the message "No meetings were found matching the selected criteria."  Changing the search criteria to more specific or more general search criteria got the same result.

The problem inexplicably went away Wednesday morning.  So we were without meeting lists for about 20 hours.

Does this seem like the same problem?  It sounds like your failures are of much shorter duration.  Should I split this discussion off to a separate issue?

When you mention the "server logs" do you mean the php error logs?  or other logs?  I will begin looking at our logs today.

**Comment by aanecswebmaster** [comment] 2021-02-12 01:02
We have had another occurrence, again associated with a meeting update.

Details:  The office staff updated a meeting this afternoon, this time unchecking a "Temporarily Closed" checkbox for the meeting.  Note a very different change than to the previous instance.
Her method was to use the Bulk Edit button with that meeting selected.  
Then she tried the meeting search and got the same "no meetings found" message no matter what the  search criteria.
Then she reversed the change using the same bulk actions to check the Temporarily Closed option.  No change in search..
Then, a few minutes later she chose the edit option for that meeting, and in edit, checked and unchecked the checkbox for that meeting and updated the listing.  
The problem was fixed, search was returning results again.

That documents our latest occurrence.

Questions on how to proceed:
1. The install of release 3.10.0 occurred at just about the beginning of our problems.  I want to back that off but cannot find where to download the previous release.  
2. Also, how do I go to an earlier release? Just uninstall the plugin and install the previous release?
3. Now that we have a more precise time to consider, what logs should I be looking at? php error log? other?
4. I get the sense that this is sufficiently different tha @mikepoconnor4 problem that it should be split off into a separate Issue?

In the meantime, I will create a clone of our site and see if I can reproduce the problem there.  If so, we will have a test system to work with without disturbing  the production system.  Meanwhile, we know to check that search is working after every meeting change.

**Comment by tech2serve** [comment] 2021-02-12 01:42
Hey @aanecswebmaster (Ross) --

You indicated above you were on v3.9.6 when you had the problem start. I didn't release v3.10.0 until quite late on Tuesday night. I'm skeptical that is related, but if you want to roll back, you can download the v3.9.6 zip file from [Wordpress.org 12-Step-Meeting-List](https://wordpress.org/plugins/12-step-meeting-list/advanced/) or here at GitHub. Once downloaded, you can upload/install the zip file through your plugins page.

So for both you and @mikepoconnor4, I suggest looking at commonalities between your websites, in particular other plugins you have installed.  I just looked at both your sites and both meeting lists showed up without a hitch. But I do see errors in the console for both your sites. For Ross:

![image](https://user-images.githubusercontent.com/31904316/107720238-f3c45280-6ca7-11eb-85f1-39ae4a3412bd.png)

I'm not an HTML expert by any means, but on my dev site there is nothing trying to preload the meeting list. Do you have some sort of caching plugin running? If so, try disabling it, and see if the errors in your console clear up. And some of my compadres here in C4R are smarter than me in this stuff, so I'll cc them.

Looks like Mike has some errors too that *could* be contributing. 

Anyway, that is where I would start.

cc: @code4recovery/tsml-contributors

**Comment by aanecswebmaster** [comment] 2021-02-13 23:19
Here is an update:
First a puzzle.  Our site has been running tsml for many months without a hitch,   Then the problem appeared Tuesday.  I have racked my brain to figure out what changed on our site.  No idea.

My diagnostic work:

1. I have cloned our production site to create a test site.
2. This morning I was able to reproduce the problem freely on both the test and the production system by using the Bulk Actions option to turn the Temporarily Closed flag on or off.  Almost always, using the Bulk Actions to change the flag created the problem.  But occasionally it did not.  So still a bit of randomness.
3. But this morning gave me logs centered on the problem occurrence.  The linux system logs, the website logs and the PHP error logs all showed no problems indicated.
4. Bad news though.  This afternoon I have been unable to reproduce the problem at all on either the production or test systems.  
5. I was NOT able to create the problem by editing the meeting directly  (not using Bulk Actions) changing either the Temporary Closed or any other field or flag.
6. I was able to remove all the browser console problems by changing a couple of settings for the Autooptimize plugin.  The above testing was after these were fixed.

The logs are available if someone smarter than I want to look at them.  

I will be trying to reproduce periodically to see how often the problem is reproducible.
Is there some sort of trace or something I can turn on?

**Comment by tech2serve** [comment] 2021-02-13 23:34
@aanecswebmaster, 

If you haven't already done so, turn on Wordpress debugging. There are plenty of Internet articles on how to do that. That should also increase the output you see in the console from the plugin.

Tim

**Comment by aanecswebmaster** [comment] 2021-02-13 23:34
I looked at what plugins were updated just before the onset of the problem.  The Disable Comments plugin was updated Monday morning.  We first saw the problem Tuesday morning, but given how few updates we get and the intermittent nature of the problem, that is possible.  I have disabled the plugin on  production. Not on test so that we can continue to try to reproduce.

**Comment by aanecswebmaster** [comment] 2021-02-13 23:45
@tech2serve suggested that we compare our systems.  Here is list of plugins:
12 Step Meeting List
12 Step Meeting PDF Generator
Autoptimize
Bing Webmaster Url Submission
Disable Comments
Elementor Pro
Formidable Forms Pro
Formidable MailChimp
Formidable PayPal Standard
Formidable Stripe
Formidable Views
Google XML Sitemaps
Limit Login Attempts Reloaded
Site Kit by Google
Smush
Tawk.to Live Chat
Tockify Events Calendar
User Role Editor
WP Google Search
WP Mail SMTP
WP Super Cache

**Comment by tech2serve** [comment] 2021-02-22 23:38
Hey @mikepoconnor4,

Is this what you were seeing with the list wasn't coming up?

<img width="711" alt="image" src="https://user-images.githubusercontent.com/31904316/108784311-be83f400-7534-11eb-9414-3133d6a5363c.png">

**Comment by mikepoconnor4** [comment] 2021-02-23 15:42
Yes.

I still need to get together with someone else here to review the server logs. We just haven't been able to find a time to get together. Hopefully next week.

**Comment by aanecswebmaster** [comment] 2021-02-23 16:23
The latest update for NE Central Service

1. We have not experienced the problem since the last post,  Nor have we been able to recreated it on test or production systems.
2. I have put various debugging and logging tools in place to investigate of problem does recur.  On next recurrence, office will call me while it is not working and I will turn on the debugging tools and see what I find.
I don't know news is bad news.  :-)

**Comment by tech2serve** [comment] 2021-02-23 18:33
> Yes.
> 
Excellent. This almost looks more like a Page Not Found error. 

One thing you might try is to go into Settings-->Permalinks, and click Save. You don't need to change any of the values first. Simply clicking Save will refresh the links and **might** resolve the issue. However, normally when I see something like this, the symptom is not so intermittent!

> I still need to get together with someone else here to review the server logs. We just haven't been able to find a time to get together. Hopefully next week.

**Comment by tech2serve** [comment] 2021-02-23 18:34
> The latest update for NE Central Service
> 
>     1. We have not experienced the problem since the last post,  Nor have we been able to recreated it on test or production systems.
> 
>     2. I have put various debugging and logging tools in place to investigate of problem does recur.  On next recurrence, office will call me while it is not working and I will turn on the debugging tools and see what I find.
>        I don't know if no news is good news.  :-)

I would call it good news and move onto other things :-)

**Comment by Carlsans** [comment] 2021-03-07 13:42
Do you have any backup system that would be sheduled in the morning ? Sometime they load the server. That would explain some of your issues(but maybe not your main issue...)

**Comment by aanecswebmaster** [comment] 2021-03-12 15:42
Another update from aaneok.org, Northeast Central Service

 We have experienced the problem a few more times, and narrowed down some info.
(by "condition" in what follows I mean searches for meetings get the "no results found for search criteria" no matter what the search criteria are.

1. The condition is always triggered when we mark a single meeting Temporarily Closed by checking a single meeting in the meeting list and then using bulk actions to mark it Temp Closed.  The condition is not triggered by editing the meeting and marking it Temp Closed checkbox, only when using bulk action.
2. Once triggered, the condition continues until the offending meeting change is reversed by editing the meeting entry.

So the two puzzles are (a) why does marking a meeting TC with bulk actions trigger the condition and (b) why do meeting searches fail while the condition is happening.  And I guess (c) what about editing and reversing the TC change causes the condition to go away?

I do not know enough about the differences between making a change by bulk action vs making a change by editing.

We were able to get the condition to occur on our test system, and there we could leave it long enough to look at what happens during a search with the condition active.  The attached spreadsheet is the QueryMonitor plugin output for a failed search during the condition.  There were no debug.log entries for this time period. (WP debugging was all options on)
Perhaps someone who knows what a search looks like can get a clue for puzzle (b).

It would be nice to catch the triggering, puzzle (b) in the act and get diagnostic data for that.

[Queries while meetings not found.xlsx](https://github.com/code4recovery/12-step-meeting-list/files/6131079/Queries.while.meetings.not.found.xlsx)

**Comment by tech2serve** [comment] 2021-03-12 20:59
@aanecswebmaster,

Does your test site have PHP debugging turned on? Are you seeing any notices?

I'm finding I am getting a PHP notice when I try to use bulk change of TC, but still can't duplicate the meetings not found. 

BTW, do you get "Page not found" or a no matching meetings error?

**Comment by aanecswebmaster** [comment] 2021-03-13 17:09
Yes, PHP debugging turned on  with all options marked true.  No messages.
The message is No matching meetings on the TSML page.
We still cannot reproduce the condition at will.  It is intermittent and fairly rare.  Frustrating.
For your purposes, this is not a high priority problem since we have a way to immediately make the condition go away. 
Thanks for working on  it.  

If we can make the problem recur, we can give you credentials to log into our test system yourselves if that will be helpful.

**Comment by tech2serve** [comment] 2021-03-13 20:10
Thanks, Ross. I do get a notice so we'll try to resolve that and see if it makes your problem go away.

Hopefully @mikepoconnor4 will return and share if he was also using the bulk edit mode.

**Comment by mikepoconnor4** [comment] 2021-03-13 20:32
Hi - sorry for going quiet for a while. We just got together here yesterday to get on the server and check logs. We didn't find anything hopping out at us. We're going to do a light night check with deactivating other plugins to see if we can get to a clean console when we do a search.

Relative to your question - we haven't been using bulk edit mode. I did notice a strange one the other day. I checked the search and it was fine. Then I edited a meeting that was going from hybrid to physical only - so I removed the zoom info. After I did the update, I returned to the search and noticed it wasn't returning results - a few minutes later it returned to normal again.

One question we had. When a search is done, I assume the search is occurring on our local server - the search isn't occurring on one of your servers, correct?

**Comment by tech2serve** [comment] 2021-03-13 20:35
> One question we had. When a search is done, I assume the search is occurring on our local server - the search isn't occurring on one of your servers, correct?

Correct. The only time a server of ours is used is with the beta API gateway for geocoding. 

I'm still wondering about caching with your site and if that is the culprit.

**Comment by 97eighty** [comment] 2021-10-30 19:20
Closing this issue. Open again if issue continues.

**Closed by 97eighty** 2021-10-30 19:20 UTC
Labels: support/question
