### ISSUE TITLE
"Able to attend in person" not saving

### ISSUE THREAD

**Issue by julien-paris** [code4recovery/12-step-meeting-list#497] opened 2021-08-11 10:33 UTC
We ran into an issue where we were not able to save "Yes" on the "Can I currently attend this meeting in person?" location setting. 
I tested on a different meeting, and it worked. 
So the issue was with a particular meeting. 
Also, the address was resolved by Google and the pin was correctly placed on map. 

I rolled back to 12 Step Meeting list 3.11.2 and this resolved my issue.

**Comment by joshreisner** [comment] 2021-08-11 21:33
Hi Julien, please provide some more info so we can try to reproduce the issue:

what's the address and/or the URL of the meeting on your site?

what change were you trying to make? 

what happened when you tried to edit it? was the button disabled, or did it go through but the setting revert to "No?"

any error messages?

Thanks

**Comment by julien-paris** [comment] 2021-08-11 21:45
Hi Josh, thx for the followup. 
The meeting is: 
https://alcoholics-anonymous.eu/meetings/international-group-2/

The change I was trying to make was on the "Can I currently attend this meeting in person?"
it was set to No. I would switch to Yes, save, and it was back on No.

Oddly enough, I tested another random meeting, and I was able to switch. So it was only on this particular meeting that I couldnt change. 

Does this answer your questions?

**Comment by joshreisner** [comment] 2021-08-11 22:50
Hm, I tried adding it to our demo site with the same data and it looks fine to me. I'm about to switch "Can I attend in person" back and forth without issue https://demo.code4recovery.org/meetings/international-group

Data looks fine on your site.

![Screen Shot 2021-08-11 at 3 46 27 PM](https://user-images.githubusercontent.com/1551689/129113397-5b2de2c0-3897-4291-a6a7-abd6f39386e7.png)

Looks like you've overridden the meeting detail page, but I don't see why that should make a difference since the issue is apparent on the edit screen.

Are there any other customizations in your child theme? Like for example is there an address override for this address?

**Comment by joshreisner** [comment] 2021-08-11 23:03
If you're comfortable updating again that might help us identify the issue. Can't really think of what the issue could be

**Comment by julien-paris** [comment] 2021-08-11 23:07
Ok done. And the problem persists.
https://alcoholics-anonymous.eu/meetings/international-group-2/

**Comment by joshreisner** [comment] 2021-08-11 23:40
Thanks Julien, that was very helpful. It looks like the reason why it's not saving is it thinks the location is approximate, even though the geocoder is saying it's not. The JSON now says:

![Screen Shot 2021-08-11 at 4 10 45 PM](https://user-images.githubusercontent.com/1551689/129116617-facd0f56-e584-4da1-bccb-c527441128f0.png)

I hope you don't mind but I have an old login to your site and I wanted to see what the form is doing. When the page loads the hidden `approximate` field is set to `yes`

![Screen Shot 2021-08-11 at 4 34 15 PM](https://user-images.githubusercontent.com/1551689/129116863-872c357d-c45b-4ddd-8927-c3a33d030d51.png)

But then the geocode fires and gets back `no`

![Screen Shot 2021-08-11 at 4 14 34 PM](https://user-images.githubusercontent.com/1551689/129116885-438c654f-e789-408f-84ae-dbe3a9e59b5c.png)

Which then sets the form to `no`

![Screen Shot 2021-08-11 at 4 15 28 PM](https://user-images.githubusercontent.com/1551689/129116904-98277a12-a099-4f24-81ba-d33dbd3f2666.png)

But then when it's saved the new value is not applied.

Do you have database access? I'm wondering if you could run this query and let us know what it says: `select * from wp_postmeta where post_id = 11543 and meta_key = 'approximate'` -- i'm guessing it says `yes`

And then send us this value (it's going to be big) `select option_value from wp_options where option_name = 'tsml_addresses'` 

But if not that's ok I think we have enough to go on now. Thanks

**Comment by julien-paris** [comment] 2021-08-11 23:56
Not sure I ran the query on the right DB tbh

https://prnt.sc/1n3jele

**Comment by julien-paris** [comment] 2021-08-12 00:01
Aha better:
does this answer your question? 
https://prnt.sc/1n3my33

**Comment by joshreisner** [comment] 2021-08-12 02:48
Ok could you do two more?

`select * from wp_CERpostmeta where post_id = 11543`

`select option_value from wp_CERoptions where option_name = 'tsml_addresses'`

for the first one a screenshot is fine, for the second one i need to see the very long value that is returned

thanks

**Comment by julien-paris** [comment] 2021-08-12 10:01
for the first:
![image](https://user-images.githubusercontent.com/73740354/129178197-76372e01-a3d6-4984-b788-fa46a7ac4492.png)

**Comment by julien-paris** [comment] 2021-08-12 10:03
For the second I still get an empty response.
How can I do a db dump without the users? 
Can I email it to you? 
Also, maybe the link to the json file may help?

**Comment by joshreisner** [comment] 2021-08-12 15:04
Thanks Julien, that result was very helpful. 

Looks like we're not set up to receive a database now, but I just committed a change to the next version of the plugin that hopefully will address this issue. Let's see if it works and take it from there.

**Comment by julien-paris** [comment] 2021-08-12 15:06
Awesome :)
Thanks to you for your diligence.

**Comment by joshreisner** [comment] 2021-10-03 15:38
Hopefully this is fixed now with the release of `3.12`

**Closed by joshreisner** 2021-10-03 15:38 UTC
