### ISSUE TITLE
Meeting Occurrence Every Second Week.

### ISSUE THREAD

**Issue by Jimmyjoe5217** [code4recovery/12-step-meeting-list#156] opened 2020-09-03 11:40 UTC
I have a meeting that is moving to every second Friday (one week on, one week off).  Similar to Issue #145 Monthly Meeting, is there a way to schedule a meeting to occur every second week only ?

**Comment by tech2serve** [comment] 2020-09-09 16:05
Duplicate of #145

**Closed by tech2serve** 2020-09-09 16:05 UTC
Labels: duplicate, new feature/enhancement
