### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by Area82** [code4recovery/12-step-meeting-list#380] opened 2021-06-22 13:06 UTC
Hello, 

I suddenly can't create new meeting listings. Only edit previous listings. I am signed in as the administrator but whenever I want to publish a new meeting there is no publish button. There is a "submit for review" button in it's place. Whenever I click that button or try to save it as a draft, I get this error "Sorry, you are not allowed to edit this post."

**Comment by joshreisner** [comment] 2021-06-22 14:08
Unless someone has installed a new plugin, my guess based on [this thread](https://wordpress.org/support/topic/submit-for-review-in-wordpress-5-0/) is that your user account has a "Contributor" level. See if an administrator can upgrade you to an Author [or above](https://wordpress.org/support/article/roles-and-capabilities/) so you can Publish again

**Comment by Area82** [comment] 2021-06-22 17:03
No new apps recently. I am the administrator. There are no other users on the account.

**Comment by tech2serve** [comment] 2021-06-22 17:05
You can edit and publish existing meetings?

**Comment by Area82** [comment] 2021-06-22 17:09
Yes, it allows me to edit and publish any existing meetings.

**Comment by tech2serve** [comment] 2021-06-22 17:17
Please open up a developer console in your browser and watch for errors and warnings.

Provide screen caps of your admin page (block out PII).

Please think through what might have changed with your system. TSML has NOT changed, and so the cause is likely to be something else.

**Comment by Area82** [comment] 2021-06-22 18:12
<img width="479" alt="Screen Shot 2021-06-22 at 2 22 00 PM" src="https://user-images.githubusercontent.com/86302482/122977916-4c99ab00-d36c-11eb-933a-5337abcf0228.png">
![Upload
<img width="1275" alt="Screen Shot 2021-06-22 at 3 10 12 PM" src="https://user-images.githubusercontent.com/86302482/122977920-4d324180-d36c-11eb-98c5-038a63e0fc08.png">
ing Screen Shot 2021-06-22 at 3.10.25 PM.png…]()

**Comment by Area82** [comment] 2021-06-22 18:15
I have just recently taken over the website and I have updated the PhP and SSL as they were out of date. But this issue was happening before I updated those.

**Comment by brianw-area24** [comment] 2021-06-24 05:22
My guess is you have the same issue if you try to make a new Post on your site, not just a meeting. Maybe also making a new Page.

I have not seen those two warning messages before. When I looked for them in the code, they are not part of TSML plugin, but rather WordPress itself. Doing an Internet search for the second message "You are currently editing the page that shows your latest posts", there were a lot of suggestions, and lots of interesting reading.

First, I'd suggest making a backup of the database, and maybe exporting the site. 

Next, I'd probably run https://your-domain-name/wp-admin/maint/repair.php, you will probably need to add a line to the wp-config.php file, and be sure to remove this line when you're finished. 
See: https://bwit.blog/fix-you-are-currently-editing-the-page-that-shows-your-latest-posts-wordpress/

This page was also an interesting read:
https://wordpress.org/support/topic/cannot-create-new-post-or-page/

Another thing to try would be to disable all other plugins, and see if the problem persists.

Again, be sure you have a current backup of your site. And don't do anything you're not comfortable doing. 

You mention updating PHP, do you know the old version number, and the new one?

Brian W.

**Comment by 97eighty** [comment] 2021-10-30 19:17
Closing this. Reopen I there is additional information.

**Closed by 97eighty** 2021-10-30 19:17 UTC
Labels: support/question, need more information
